import {topics,types,generate} from './catalog.js';
import {checkAnswer} from './answer.js';import {fresh,restore,record,key} from './progress.js';import {visual} from './visual.js';
const $=id=>document.getElementById(id),option=(value,text)=>new Option(text,value);
let state=fresh();try{state=restore(localStorage.getItem(key));}catch{$('storage-status').textContent='Speicher nicht verfügbar. Fortschritt gilt nur bis zum Schließen dieser Seite.';}
let mode='train',current,assisted=false,recorded=false,finished=false,hints=0,queue=[],index=0,results=[],lastId='';
const randomSeed=()=>crypto.getRandomValues(new Uint32Array(1))[0];
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('storage-status').textContent='Fortschritt konnte nicht gespeichert werden. Bitte exportiere ihn vor dem Schließen.';}stats();}
function stats(){$('attempted').textContent=state.attempted;$('clean').textContent=state.clean;$('error-count').textContent=state.errors.length;$('topic-progress').replaceChildren();for(const t of topics){const ts=types.filter(x=>x.topic===t.id),done=ts.filter(x=>(state.byType[x.id]?.clean??0)>0).length;const p=document.createElement('p');p.textContent=`${t.name}: ${done} / ${ts.length} Typen mindestens einmal ohne Hilfe gelöst`;$('topic-progress').append(p);}}
function pool(){return types.filter(t=>t.topic===$('topic').value&&($('level').value==='all'||String(t.level)===$('level').value));}
function updateTypes(){const ts=pool();$('type').replaceChildren(option('all','Alle Typen im Thema'),...ts.map(t=>option(t.id,t.title)));$('pool-count').textContent=`${ts.length} passende Aufgabentypen · neue Zahlen bei jeder Runde`;}
function modeUI(){for(const [button,m] of [['train','train'],['review','review'],['test','test']])$(button).setAttribute('aria-pressed',String(mode===m));for(const id of ['topic','level','type'])$(id).disabled=mode!=='train';$('hint').disabled=mode==='test';$('solution').disabled=mode==='test';$('rule-box').hidden=mode==='test';$('mode-label').textContent={train:'Freies Üben',review:'Deine Fehlerkartei',test:'Gemischter Test'}[mode];}
function show(q){current=q;assisted=false;recorded=false;finished=false;hints=0;$('summary').hidden=true;$('exercise').hidden=false;$('exercise').dataset.type=q.id;$('exercise').dataset.seed=q.seed;
 $('task-title').textContent=q.title;$('prompt').textContent=q.prompt;$('scope').textContent=`Rahmenlehrplan: ${q.scope}`;$('difficulty').textContent=`Anspruch ${q.level} / 3`;
 $('topic-intro').textContent=topics.find(t=>t.id===q.topic).intro;$('rule').textContent=q.rule;$('rule-box').open=false;$('steps').replaceChildren();$('answer').value='';$('answer').disabled=false;$('check').disabled=false;$('feedback').textContent='';$('feedback').className='feedback';$('answer').removeAttribute('aria-invalid');$('seed').textContent=`Aufgabenkennung: ${q.id} · Variante ${q.seed}`;
 $('answer-help').textContent=q.kind==='set'?'Alle Lösungen, mit Semikolon getrennt (z. B. −2; 2). Keine Lösung: „keine“.':q.round!==undefined?'Nur die Zahl, ohne Einheit. Auf zwei Nachkommastellen runden. Taschenrechner erlaubt.':'Nur die Zahl, ohne Einheit. Exakten Bruch (z. B. 2/3) oder genaue Dezimalzahl eingeben.';
 $('visual').innerHTML=visual(q);$('visual').hidden=!$('visual').innerHTML;$('next').textContent=mode==='test'?'Überspringen →':'Nächste Aufgabe →';$('position').textContent=mode==='test'?`${index+1} / 10`:mode==='review'?`${state.errors.length} offen`:'';modeUI();}
function freeTask(){let ts=pool();if($('type').value!=='all')ts=ts.filter(t=>t.id===$('type').value);if(ts.length>1)ts=ts.filter(t=>t.id!==lastId);if(!ts.length)return;const t=ts[randomSeed()%ts.length];lastId=t.id;show(generate(t.id,randomSeed()));}
function reviewTask(){if(!state.errors.length){current=null;$('summary').hidden=true;$('exercise').hidden=false;$('task-title').textContent='Alles erledigt';$('prompt').textContent='In deiner Fehlerkartei ist gerade keine Aufgabe offen.';$('visual').hidden=true;$('steps').replaceChildren();$('rule-box').hidden=true;$('position').textContent='0 offen';$('feedback').textContent='Deine Fehlerkartei ist leer. Wähle „Frei üben“ oder starte einen Test.';$('answer').disabled=true;$('check').disabled=true;$('hint').disabled=true;$('solution').disabled=true;$('next').disabled=true;return;}$('next').disabled=false;const e=state.errors[index%state.errors.length];show(generate(e.id,e.seed));}
function start(m){
 mode=m;index=0;results=[];$('next').disabled=false;modeUI();if(m==='train'){freeTask();return;}if(m==='review'){reviewTask();return;}
 queue=topics.map(t=>{const ts=types.filter(x=>x.topic===t.id);return {id:ts[randomSeed()%ts.length].id,seed:randomSeed()};});queue.push({id:types[randomSeed()%types.length].id,seed:randomSeed()});for(let j=queue.length-1;j>0;j--){const k=randomSeed()%(j+1);[queue[j],queue[k]]=[queue[k],queue[j]];}show(generate(queue[0].id,queue[0].seed));}
function valueFeedback(status){return {correct:assisted||recorded?'Richtig! Du hast die Aufgabe im Üben gelöst.':'Richtig! Auf Anhieb ohne Hilfe gelöst.',invalid:'Das Format passt noch nicht. Gib eine Zahl oder einen Bruch ein; mehrere Lösungen mit Semikolon.',missing:'Ein Teil stimmt. Es fehlen noch Lösungen – denke auch an das zweite Vorzeichen.',sign:'Der Betrag stimmt, aber das Vorzeichen nicht. Prüfe die Minuszeichen.',wrong:'Noch nicht richtig. Prüfe Rechenzeichen und Einsetzen. Ein Hinweis kann dir den nächsten Schritt zeigen.'}[status];}
$('answer-form').addEventListener('submit',e=>{e.preventDefault();if(!current||finished)return;const {status}=checkAnswer($('answer').value,current);$('feedback').textContent=valueFeedback(status);$('feedback').className=`feedback ${status==='correct'?'good':'bad'}`;$('answer').setAttribute('aria-invalid',String(status!=='correct'));
 if(status==='invalid')return;
 if(!recorded){state=record(state,current,status==='correct',assisted);recorded=true;save();if(mode==='test')results.push({title:current.title,correct:status==='correct',skipped:false});}
 if(status==='correct'||mode==='test'){finished=true;$('answer').disabled=true;$('check').disabled=true;$('next').textContent=mode==='test'&&index===9?'Test auswerten →':'Nächste Aufgabe →';}
 if(mode==='test'&&status!=='correct')$('feedback').textContent='Noch nicht richtig. Der Versuch ist gespeichert. Nach dem Test findest du die Aufgabe mit Lösung in der Fehlerkartei.';
});
function help(all=false){if(mode==='test'||!current)return;assisted=true;const limit=all?current.steps.length:Math.min(hints+1,current.steps.length);for(;hints<limit;hints++){const li=document.createElement('li');li.textContent=current.steps[hints];$('steps').append(li);}if(all&&!recorded){state=record(state,current,false,true);recorded=true;save();}$('hint').disabled=hints===current.steps.length;}
$('hint').onclick=()=>help();$('solution').onclick=()=>help(true);$('rule-box').addEventListener('toggle',()=>{if($('rule-box').open)assisted=true;});
function summary(){const score=results.filter(r=>r.correct).length;state.tests.push({date:new Date().toISOString(),score});state.tests=state.tests.slice(-20);save();$('exercise').hidden=true;$('summary').hidden=false;$('summary').replaceChildren();const h=document.createElement('h2');h.textContent=`${score} von 10 richtig`;$('summary').append(h);const p=document.createElement('p');p.textContent='Ein Zwischenstand, keine Note. Die Aufgaben mit Fehlern oder ohne Antwort warten in deiner Fehlerkartei.';$('summary').append(p);const ul=document.createElement('ul');for(const r of results){const li=document.createElement('li');li.textContent=`${r.correct?'Richtig':r.skipped?'Übersprungen':'Wiederholen'} · ${r.title}`;ul.append(li);}$('summary').append(ul);$('position').textContent='Abgeschlossen';}
$('next').onclick=()=>{if(mode==='train'){freeTask();return;}if(mode==='review'){if(!finished)index++;reviewTask();return;}if(!recorded){state=record(state,current,false,false);results.push({title:current.title,correct:false,skipped:true});save();}index++;if(index===10){summary();return;}show(generate(queue[index].id,queue[index].seed));};
for(const [id,m]of [['train','train'],['review','review'],['test','test']])$(id).onclick=()=>start(m);
$('topic').replaceChildren(...topics.map(t=>option(t.id,t.name)));$('topic').onchange=()=>{updateTypes();freeTask();};$('level').onchange=()=>{updateTypes();freeTask();};$('type').onchange=freeTask;
$('export').onclick=()=>{const b=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='mathe-9-berlin-fortschritt.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('reset').onclick=()=>{if(!confirm('Gesamten lokalen Lernfortschritt und die Fehlerkartei löschen? Diese Aktion lässt sich nicht rückgängig machen.'))return;state=fresh();save();start('train');};
updateTypes();stats();start('train');
