import {format as f,answerText} from './answer.js';
export const topics=[
 {id:'zahlen',name:'Zahlen & Potenzen',intro:'Negative Exponenten bedeuten Kehrwerte. Gleiche Basis: beim Multiplizieren Exponenten addieren, beim Dividieren subtrahieren.'},
 {id:'gleichungen',name:'Terme & Gleichungen',intro:'Auf beiden Seiten dieselbe Umformung ausführen. Bei Produkten gilt: Ist ein Faktor null, ist das Produkt null. Eine Probe sichert dein Ergebnis.'},
 {id:'linear',name:'Lineare Funktionen',intro:'In y = mx + b ist m die Steigung und b der y-Achsenabschnitt. Zwei Punkte liefern m = Δy / Δx.'},
 {id:'quadratisch',name:'Quadratische Funktionen',intro:'Bei y = a(x − h)² + k liegt der Scheitel in S(h|k). Das Vorzeichen von a bestimmt die Öffnung. Nullstellen können fehlen, einfach oder doppelt auftreten.'},
 {id:'trigonometrie',name:'Dreiecke & Trigonometrie',intro:'Im rechtwinkligen Dreieck gilt sin α = Gegenkathete / Hypotenuse, cos α = Ankathete / Hypotenuse und tan α = Gegenkathete / Ankathete. Rechner auf Gradmaß (DEG) stellen.'},
 {id:'koerper',name:'Körper & Größen',intro:'Volumen misst den Rauminhalt, Oberfläche die äußere Fläche. Kegel und Pyramide haben V = G·h/3. Für eine Kugel gilt V = 4πr³/3 und O = 4πr².'},
 {id:'wachstum',name:'Wachstum & Schwingung',intro:'Bei diskretem Wachstum gilt N(n) = N₀·qⁿ für ganze Schritte n. Wachstum: q > 1, Zerfall: 0 < q < 1. Bei y = a·sin(bx) ist |a| die Amplitude.'},
 {id:'zufall',name:'Wahrscheinlichkeit',intro:'Entlang eines Pfads multiplizieren, getrennte passende Pfade addieren. Ohne Zurücklegen ändern sich die Anzahlen. „Mindestens einmal“ lässt sich oft über das Gegenereignis rechnen.'},
 {id:'daten',name:'Daten verstehen',intro:'Mittelwert: Summe / Anzahl. Median: Mitte der sortierten Liste. Diagramme und Stichproben kritisch prüfen: verkürzte Achsen können Unterschiede übertreiben.'}
];
export function rng(seed){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
const sin=t=>Math.sin(t*Math.PI/180),cos=t=>Math.cos(t*Math.PI/180),tan=t=>Math.tan(t*Math.PI/180);
const close=(a,b)=>Math.abs(a-b)<1e-7*Math.max(1,Math.abs(b));
const Q=(prompt,answer,work,hint,extra={})=>({prompt,answer,steps:[hint,`Rechnung: ${work}`],...extra});
export const types=[];
let topic='zahlen';
function add(id,title,level,scope,rule,build,verify){types.push({id,topic,title,level,scope,rule,build,verify:q=>verify(q.p,q.answer)});}
add('bruch-summe','Brüche addieren',1,'E/F · Wiederholung','Bringe die Brüche auf denselben Nenner; addiere dann nur die Zähler.',p=>Q(`Berechne ${p.a}/${p.b} + ${p.c}/${p.b}.`,(p.a+p.c)/p.b,`(${p.a} + ${p.c}) / ${p.b}`,`Der gemeinsame Nenner ist ${p.b}.`),(p,z)=>close(z*p.b,p.a+p.c));
add('bruch-quotient','Brüche dividieren',2,'E/F · Wiederholung','Durch einen Bruch teilen heißt mit seinem Kehrwert multiplizieren.',p=>Q(`Berechne (−${p.a}/${p.b}) : (${p.c}/${p.k}).`,-p.a*p.k/(p.b*p.c),`−${p.a}·${p.k} / (${p.b}·${p.c})`,'Drehe nur den zweiten Bruch um; das Minus bleibt.'),(p,z)=>close(z*p.c/p.k,-p.a/p.b));
add('negativer-exponent','Negativer Exponent',1,'G','Für a ≠ 0 gilt a⁻ⁿ = 1/aⁿ. Das Minus gehört zum Exponenten, nicht zum Ergebnis.',p=>Q(`Berechne ${p.a}^(−${p.n}).`,p.a**(-p.n),`1 / ${p.a}^${p.n} = 1 / ${p.a**p.n}`,'Bilde zuerst die positive Potenz, dann ihren Kehrwert.'),(p,z)=>close(z*p.a**p.n,1));
add('potenz-produkt','Potenzgesetz: Produkt',1,'G','Bei gleicher Basis werden beim Multiplizieren die Exponenten addiert.',p=>Q(`Ergänze den Exponenten e: ${p.a}^${p.n} · ${p.a}^${p.k} = ${p.a}^e.`,p.n+p.k,`${p.n} + ${p.k}`,'Die Basis bleibt unverändert.'),(p,z)=>close(p.a**z,p.a**p.n*p.a**p.k));
add('potenz-quotient','Potenzgesetz: Quotient',3,'G','Bei gleicher Basis werden beim Dividieren die Exponenten subtrahiert.',p=>Q(`Ergänze e: ${p.a}^${p.n} : ${p.a}^${p.k+3} = ${p.a}^e.`,p.n-p.k-3,`${p.n} − ${p.k+3}`,'Auch ein negativer Exponent ist möglich.'),(p,z)=>close(p.a**z*p.a**(p.k+3),p.a**p.n));
add('potenz-potenz','Eine Potenz potenzieren',2,'G','Beim Potenzieren einer Potenz werden die Exponenten multipliziert.',p=>Q(`Ergänze e: (${p.a}^${p.n})^${p.k} = ${p.a}^e.`,p.n*p.k,`${p.n} · ${p.k}`,'Nicht addieren: Die ganze Potenz wird mehrfach multipliziert.'),(p,z)=>close(p.a**z,(p.a**p.n)**p.k));
add('wissenschaftlich','Zehnerpotenzschreibweise',1,'G','Eine Zehnerpotenz verschiebt das Komma. Ein negativer Exponent ergibt eine kleine Zahl.',p=>Q(`Schreibe ${p.a} · 10^(−${p.n}) als Dezimalzahl.`,p.a*10**(-p.n),`Verschiebe das Komma ${p.n} Stellen nach links.`,'Beginne bei der Zahl vor der Zehnerpotenz.'),(p,z)=>close(z*10**p.n,p.a));
add('wurzel-einschachteln','Quadratwurzel einschätzen',2,'G','Vergleiche mit benachbarten Quadratzahlen: k² ≤ N < (k+1)² bedeutet k ≤ √N < k+1.',p=>Q(`Gesucht ist die größte ganze Zahl k mit k ≤ √${p.a*p.a+p.c}.`,Math.floor(Math.sqrt(p.a*p.a+p.c)),`Vergleiche ${p.a*p.a+p.c} mit benachbarten Quadratzahlen.`,'Suche ein Quadrat darunter und das nächste darüber.'),(p,z)=>z*z<=p.a*p.a+p.c&&(z+1)**2>p.a*p.a+p.c);
topic='gleichungen';
add('linear-loesen','Lineare Gleichung',1,'E/F · Wiederholung','Subtrahiere zuerst den konstanten Term, teile dann durch den Faktor vor x.',p=>Q(`Löse ${p.a}x + ${p.b} = ${p.a*p.x+p.b}.`,p.x,`${p.a}x = ${p.a*p.x}; x = ${p.a*p.x} / ${p.a}`,`Subtrahiere auf beiden Seiten ${p.b}.`),(p,z)=>close(p.a*z+p.b,p.a*p.x+p.b));
add('klammer-loesen','Gleichung mit Klammer',2,'E/F · Wiederholung','Du kannst zuerst durch den äußeren Faktor teilen. Danach löst du die innere Summe auf.',p=>Q(`Löse ${p.a}(x + ${p.b}) = ${p.a*(p.x+p.b)}.`,p.x,`x + ${p.b} = ${p.x+p.b}; anschließend ${p.b} subtrahieren.`,`Teile beide Seiten durch ${p.a}.`),(p,z)=>close(p.a*(z+p.b),p.a*(p.x+p.b)));
add('binom-linear','Binomische Formel: x-Term',2,'G','(x + b)² = x² + 2bx + b². Der gemischte Term entsteht zweimal.',p=>Q(`In (x + ${p.a+p.c})² = x² + Bx + C: Wie groß ist B?`,2*(p.a+p.c),`B = 2 · ${p.a+p.c}`,'Multipliziere die beiden Glieder und nimm das Doppelte.'),(p,z)=>close((2+p.a+p.c)**2-4-((p.a+p.c)**2),2*z));
add('differenz-quadrate','Differenz von Quadraten',2,'G','(x − b)(x + b) = x² − b². Die gemischten Terme heben sich auf.',p=>Q(`In (x − ${p.a+p.c})(x + ${p.a+p.c}) = x² + C: Wie groß ist C?`,-((p.a+p.c)**2),`C = −${p.a+p.c}²`,'Beachte das Minus vor dem Quadrat.'),(p,z)=>close((3-p.a-p.c)*(3+p.a+p.c),9+z));
add('quadrat-loesen','Quadratische Gleichung: ±',1,'G','Aus x² = r² folgen x = r und x = −r. Beide Zahlen haben dasselbe Quadrat.',p=>Q(`Bestimme alle reellen Lösungen von x² = ${(p.a+p.c)**2}.`,[-p.a-p.c,p.a+p.c],`x = ±√${(p.a+p.c)**2}`,'Gib beide Lösungen mit Semikolon getrennt an.',{kind:'set'}),(p,z)=>z.length===2&&z[0]!==z[1]&&z.every(v=>v*v===(p.a+p.c)**2));
add('produkt-null','Satz vom Nullprodukt',2,'G','Ein Produkt ist genau dann null, wenn mindestens einer seiner Faktoren null ist.',p=>Q(`Löse (x − ${p.a})(x + ${p.b}) = 0.`,[-p.b,p.a],`x − ${p.a} = 0 oder x + ${p.b} = 0.`,'Setze jeden Faktor einzeln gleich null.',{kind:'set'}),(p,z)=>z.length===2&&z[0]!==z[1]&&z.every(v=>(v-p.a)*(v+p.b)===0));
add('quadratisch-allgemein','Quadratische Gleichung faktorisieren',3,'G','Suche zwei Zahlen, deren Produkt der konstante Term und deren Summe der x-Koeffizient ist.',p=>Q(`Löse x² + ${p.a+p.b}x + ${p.a*p.b} = 0.`,[...new Set([-p.a,-p.b])],`(x + ${p.a})(x + ${p.b}) = 0.`,'Nutze anschließend den Satz vom Nullprodukt.',{kind:'set'}),(p,z)=>z.length===(p.a===p.b?1:2)&&z.every(v=>v*v+(p.a+p.b)*v+p.a*p.b===0));
add('lgs','Lineares Gleichungssystem',3,'G','Addiere Gleichungen so, dass eine Variable wegfällt. Setze anschließend zur Probe ein.',p=>Q(`Gegeben: x + y = ${p.x+p.b} und x − y = ${p.x-p.b}. Bestimme x.`,p.x,`2x = ${2*p.x}; teile durch 2.`,'Beim Addieren verschwinden +y und −y.'),(p,z)=>close(p.x+p.b-z,z-(p.x-p.b)));
topic='linear';
add('linear-wert','Funktionswert',1,'E/F · Wiederholung','Setze den x-Wert ein. Multipliziere vor dem Addieren.',p=>Q(`f(x) = ${p.k}x + ${p.b}. Berechne f(${p.x}).`,p.k*p.x+p.b,`${p.k}·(${p.x}) + ${p.b}`,'Negative x-Werte in Klammern einsetzen.',{graph:{kind:'line',m:p.k,b:p.b}}),(p,z)=>close((z-p.b)/p.k,p.x));
add('steigung-punkte','Steigung aus zwei Punkten',2,'G','Die Steigung ist die Änderung in y geteilt durch die Änderung in x.',p=>Q(`Eine Gerade geht durch A(${p.x}|${p.b}) und B(${p.x+p.a}|${p.b+p.c}). Bestimme m.`,p.c/p.a,`m = (${p.b+p.c} − ${p.b}) / (${p.x+p.a} − (${p.x}))`,'Berechne Δy und Δx in derselben Richtung.'),(p,z)=>close(z*p.a+p.b,p.b+p.c));
add('achsenabschnitt','Achsenabschnitt aus Punkt',2,'G','Aus y = mx + b folgt b = y − mx.',p=>Q(`Eine Gerade hat m = ${p.k} und enthält P(${p.x}|${p.k*p.x+p.b}). Bestimme b.`,p.b,`b = ${p.k*p.x+p.b} − ${p.k}·(${p.x})`,'Setze den Punkt in y = mx + b ein.'),(p,z)=>close(p.k*p.x+z,p.k*p.x+p.b));
add('lineare-nullstelle','Lineare Nullstelle',1,'E/F · Wiederholung','An der Nullstelle gilt y = 0. Löse die entstehende lineare Gleichung.',p=>Q(`Bestimme die Nullstelle von f(x) = ${p.a}x + ${p.b}.`,-p.b/p.a,`${p.a}x = −${p.b}; x = −${p.b}/${p.a}`,'Setze den Funktionsterm gleich null.',{graph:{kind:'line',m:p.a,b:p.b}}),(p,z)=>close(p.a*z+p.b,0));
add('schnittpunkt','Schnittpunkt zweier Geraden',3,'G','Am Schnittpunkt haben beide Geraden denselben y-Wert. Setze die Terme gleich.',p=>Q(`f(x) = ${p.k+1}x + ${p.b}, g(x) = x + ${p.b+p.k*p.x}. Bestimme die x-Koordinate des Schnittpunkts.`,p.x,`${p.k}x = ${p.k*p.x}; teile durch ${p.k}.`,'Bringe alle x-Terme auf eine Seite.'),(p,z)=>close((p.k+1)*z+p.b,z+p.b+p.k*p.x));
add('kosten','Lineares Kostenmodell',2,'G · Modellieren','Gesamtkosten = Grundpreis + Preis je Einheit · Anzahl. Ein Modell gilt nur unter seinen Annahmen.',p=>Q(`Ein Leihrad kostet ${p.b} € Grundpreis und ${p.k} € je Stunde. Wie viel kosten ${p.a} Stunden (in €)?`,p.b+p.k*p.a,`${p.b} + ${p.k}·${p.a}`,'Der Grundpreis fällt nur einmal an.'),(p,z)=>close((z-p.b)/p.k,p.a));
add('linear-invers','Eingabewert finden',2,'E/F · Wiederholung','Ein vorgegebener Ausgabewert führt zu einer Gleichung. Mache Addition und Multiplikation rückgängig.',p=>Q(`f(x) = ${p.a}x − ${p.b}. Für welches x gilt f(x) = ${p.a*p.x-p.b}?`,p.x,`${p.a}x = ${p.a*p.x}; durch ${p.a} teilen.`,`Addiere zuerst ${p.b}.`),(p,z)=>close(p.a*z-p.b,p.a*p.x-p.b));
add('aenderung','Änderungsrate anwenden',2,'G','Bei einer linearen Funktion gilt Δy = m·Δx, unabhängig vom Achsenabschnitt.',p=>Q(`f(x) = −${p.k}x + ${p.b}. x steigt um ${p.a}. Wie groß ist Δy (mit Vorzeichen)?`,-p.k*p.a,`Δy = −${p.k}·${p.a}`,'Eine negative Steigung bedeutet: y fällt.'),(p,z)=>close(z,(-p.k*(p.x+p.a)+p.b)-(-p.k*p.x+p.b)));
topic='quadratisch';
add('parabel-wert','Parabel: Funktionswert',1,'G','Setze x ein, berechne zuerst die Klammer, dann das Quadrat und zuletzt die Verschiebung.',p=>Q(`f(x) = ${p.k}(x − ${p.a})² + ${p.b}. Berechne f(${p.x}).`,p.k*(p.x-p.a)**2+p.b,`${p.k}·(${p.x-p.a})² + ${p.b}`,'Beachte die Reihenfolge der Rechenoperationen.',{graph:{kind:'parabola',a:p.k,h:p.a,k:p.b}}),(p,z)=>close((z-p.b)/p.k,(p.x-p.a)**2));
add('scheitel-x','Scheitel: x-Koordinate',1,'G','Die Klammer ist am Scheitel null. Bei (x + d)² liegt die x-Koordinate bei −d.',p=>Q(`f(x) = ${p.k}(x + ${p.a+p.c})² − ${p.b}. Bestimme die x-Koordinate des Scheitels.`,-p.a-p.c,`x + ${p.a+p.c} = 0; x = −${p.a+p.c}`,'Das Vorzeichen in der Klammer wird umgekehrt.'),(p,z)=>close((z+p.a+p.c)**2,0));
add('scheitel-y','Scheitel: y-Koordinate',1,'G','Am Scheitel ist der quadratische Anteil null. Übrig bleibt die Verschiebung außerhalb der Klammer.',p=>Q(`f(x) = −${p.k}(x − ${p.a})² + ${p.b+p.c}. Bestimme die y-Koordinate des Scheitels.`,p.b+p.c,`f(${p.a}) = −${p.k}·0² + ${p.b+p.c}`,'Setze die Klammer gleich null.'),(p,z)=>close(z,-p.k*(p.a-p.a)**2+p.b+p.c));
add('parabel-nullstellen','Verschobene Parabel: Nullstellen',2,'G','Isoliere das Quadrat. Ziehe die Wurzel mit beiden Vorzeichen und löse beide linearen Gleichungen.',p=>Q(`Bestimme alle Nullstellen von f(x) = (x − ${p.a})² − ${p.b*p.b}.`,[p.a-p.b,p.a+p.b],`x − ${p.a} = ±${p.b}; x = ${p.a} ± ${p.b}`,'Zuerst den konstanten Term auf die andere Seite bringen.',{kind:'set',graph:{kind:'parabola',a:1,h:p.a,k:-p.b*p.b}}),(p,z)=>z.length===2&&z[0]!==z[1]&&z.every(v=>(v-p.a)**2===p.b*p.b));
add('minimum','Minimalwert',2,'G','Ein Quadrat ist nie negativ. Bei positivem Vorfaktor wird der kleinste Wert am Scheitel erreicht.',p=>Q(`Was ist der kleinste Funktionswert von f(x) = ${p.k}(x − ${p.a})² − ${p.b+p.c} für reelle x?`,-p.b-p.c,`Bei x = ${p.a} ist das Quadrat 0.`,'Der Vorfaktor ist positiv; die Parabel öffnet nach oben.'),(p,z)=>close(z,-p.b-p.c)&&p.k>0);
add('streckfaktor','Streckfaktor bestimmen',3,'G','Setze den bekannten Punkt in die Scheitelform ein und teile durch das Quadrat.',p=>Q(`f(x) = A(x − ${p.a})² + ${p.b} und f(${p.a+p.c}) = ${p.k*p.c*p.c+p.b}. Bestimme A.`,p.k,`A·${p.c*p.c} = ${p.k*p.c*p.c}; A = ${p.k*p.c*p.c}/${p.c*p.c}`,'Subtrahiere zuerst den y-Wert des Scheitels.'),(p,z)=>close(z*p.c*p.c+p.b,p.k*p.c*p.c+p.b));
add('symmetrie','Spiegelpunkt an der Parabel',2,'G','Eine Parabel in Scheitelform ist zur Geraden x = h symmetrisch. Spiegelpunkte haben denselben Abstand zu h.',p=>Q(`f(x) = (x − ${p.a})² + ${p.b}. Welcher andere x-Wert hat denselben Funktionswert wie x = ${p.a+p.c}?`,p.a-p.c,`x₂ = ${p.a} − ${p.c}`,'Der erste Punkt liegt rechts vom Scheitel. Gehe gleich weit nach links.'),(p,z)=>z!==p.a+p.c&&close((z-p.a)**2,p.c*p.c));
add('loesungsanzahl','Anzahl reeller Lösungen',3,'G','Ein reelles Quadrat kann positiv oder null sein, aber nicht negativ. Daraus folgen zwei, eine oder keine Lösung.',p=>{const d=[-p.b,0,p.b][p.n%3];return Q(`Wie viele verschiedene reelle Lösungen hat (x − ${p.a})² = ${d}?`,d<0?0:d===0?1:2,`Die rechte Seite ist ${d<0?'negativ':d===0?'null':'positiv'}.`,'Entscheide anhand des Vorzeichens, ohne auszurechnen.');},(p,z)=>z===([0,1,2][p.n%3]));
topic='trigonometrie';
const tri=p=>({triangle:{a:p.a,b:p.b}});
add('pythagoras','Pythagoras: Hypotenuse',1,'E/F · Wiederholung','Im rechtwinkligen Dreieck gilt c² = a² + b². Die Hypotenuse liegt gegenüber dem rechten Winkel.',p=>Q(`Ein rechtwinkliges Dreieck hat Katheten ${p.a} cm und ${p.b} cm. Wie lang ist die Hypotenuse in cm?`,Math.hypot(p.a,p.b),`c = √(${p.a}² + ${p.b}²)`,'Addiere die Quadrate und ziehe die Wurzel.',{round:2,...tri(p)}),(p,z)=>close(z*z,p.a*p.a+p.b*p.b));
add('sin-seite','Gegenkathete mit Sinus',1,'G','sin α = Gegenkathete / Hypotenuse. Daher Gegenkathete = Hypotenuse · sin α.',p=>Q(`Rechtwinkliges Dreieck: α = ${p.t}°, Hypotenuse c = ${p.a+p.b} cm. Berechne die Gegenkathete zu α in cm.`,(p.a+p.b)*sin(p.t),`g = ${p.a+p.b}·sin(${p.t}°)`,'Nutze Sinus und stelle den Rechner auf DEG.',{round:2,triangle:{a:(p.a+p.b)*cos(p.t),b:(p.a+p.b)*sin(p.t)}}),(p,z)=>close(z/(p.a+p.b),sin(p.t)));
add('cos-seite','Ankathete mit Kosinus',1,'G','cos α = Ankathete / Hypotenuse. Daher Ankathete = Hypotenuse · cos α.',p=>Q(`Rechtwinkliges Dreieck: α = ${p.t}°, Hypotenuse c = ${p.a+p.b} cm. Berechne die Ankathete zu α in cm.`,(p.a+p.b)*cos(p.t),`a = ${p.a+p.b}·cos(${p.t}°)`,'Nutze Kosinus; gesucht ist die Seite am Winkel.',{round:2}),(p,z)=>close(z/(p.a+p.b),cos(p.t)));
add('tan-seite','Gegenkathete mit Tangens',2,'G','tan α = Gegenkathete / Ankathete. Daher Gegenkathete = Ankathete · tan α.',p=>Q(`Rechtwinkliges Dreieck: α = ${p.t}°, Ankathete ${p.a} cm. Wie lang ist die Gegenkathete in cm?`,p.a*tan(p.t),`g = ${p.a}·tan(${p.t}°)`,'Die Hypotenuse wird hier nicht benötigt.',{round:2}),(p,z)=>close(z/p.a,tan(p.t)));
add('winkel','Winkel aus zwei Katheten',2,'G','Wenn Gegen- und Ankathete bekannt sind, nutze α = arctan(Gegenkathete/Ankathete).',p=>Q(`Rechtwinkliges Dreieck: Gegenkathete zu α = ${p.b} cm, Ankathete = ${p.a} cm. Bestimme α in Grad.`,Math.atan(p.b/p.a)*180/Math.PI,`α = arctan(${p.b}/${p.a})`,'Nutze die Umkehrfunktion des Tangens im Gradmaß.',{round:2,...tri(p)}),(p,z)=>close(tan(z)*p.a,p.b));
add('sinussatz','Sinussatz: Seite',3,'G','In jedem Dreieck gilt a/sin α = b/sin β. Die Seiten liegen jeweils gegenüber ihren Winkeln.',p=>Q(`Dreieck: α = ${p.t}°, β = ${p.u}°, a = ${p.a} cm (gegenüber α). Bestimme b gegenüber β in cm.`,p.a*sin(p.u)/sin(p.t),`b = ${p.a}·sin(${p.u}°)/sin(${p.t}°)`,'Beide Winkel sind gegeben; ihre Summe ist kleiner als 180°.',{round:2}),(p,z)=>close(z*sin(p.t),p.a*sin(p.u)));
add('kosinussatz','Kosinussatz: Seite',3,'G','Für den eingeschlossenen Winkel γ gilt c² = a² + b² − 2ab·cos γ.',p=>Q(`Dreieck: a = ${p.a} cm, b = ${p.b} cm, eingeschlossener Winkel γ = ${p.t}°. Berechne die gegenüberliegende Seite c in cm.`,Math.sqrt(p.a*p.a+p.b*p.b-2*p.a*p.b*cos(p.t)),`c = √(${p.a}² + ${p.b}² − 2·${p.a}·${p.b}·cos(${p.t}°))`,'Verwende den eingeschlossenen Winkel zwischen den bekannten Seiten.',{round:2}),(p,z)=>close((p.a*p.a+p.b*p.b-z*z)/(2*p.a*p.b),cos(p.t)));
add('dreieck-flaeche','Dreiecksfläche mit Winkel',3,'G','Die Höhe auf a ist b·sin γ. Setze sie in A = a·h/2 ein.',p=>Q(`Dreieck: Seiten ${p.a} cm und ${p.b} cm schließen ${p.t}° ein. Berechne die Fläche in cm².`,p.a*p.b*sin(p.t)/2,`A = ${p.a}·${p.b}·sin(${p.t}°)/2`,'Zerlege das Dreieck mithilfe einer Höhe.',{round:2}),(p,z)=>close(2*z/p.a,p.b*sin(p.t)));
topic='koerper';
add('kegel-volumen','Kegel: Volumen',1,'G','Für einen geraden Kreiskegel gilt V = πr²h/3. Die Höhe steht senkrecht auf der Grundfläche.',p=>Q(`Gerader Kreiskegel: Radius ${p.a} cm, Höhe ${p.b} cm. Berechne V in cm³.`,Math.PI*p.a*p.a*p.b/3,`V = π·${p.a}²·${p.b}/3`,'Berechne zuerst die kreisförmige Grundfläche.',{round:2}),(p,z)=>close(z*3/p.b,Math.PI*p.a*p.a));
add('kugel-volumen','Kugel: Volumen',1,'G','Das Kugelvolumen beträgt V = 4πr³/3. Verwende den Radius, nicht den Durchmesser.',p=>Q(`Eine Kugel hat den Radius ${f(p.a+p.c/10)} cm. Berechne ihr Volumen in cm³.`,4*Math.PI*(p.a+p.c/10)**3/3,`V = 4·π·${f(p.a+p.c/10)}³/3`,'Der Radius wird hoch drei genommen.',{round:2}),(p,z)=>close(Math.cbrt(3*z/(4*Math.PI)),p.a+p.c/10));
add('kugel-oberflaeche','Kugel: Oberfläche',1,'G','Die Kugeloberfläche beträgt O = 4πr². Das Ergebnis ist eine Fläche, kein Volumen.',p=>Q(`Eine Kugel hat Radius ${f(p.a+p.c/10)} cm. Berechne ihre Oberfläche in cm².`,4*Math.PI*(p.a+p.c/10)**2,`O = 4·π·${f(p.a+p.c/10)}²`,'Das Quadrat des Radius wird mit 4π multipliziert.',{round:2}),(p,z)=>close(Math.sqrt(z/(4*Math.PI)),p.a+p.c/10));
add('pyramide','Pyramide: Volumen',2,'F/G · Vertiefung','Für jede Pyramide gilt V = G·h/3. Bei rechteckiger Grundfläche ist G = Länge · Breite.',p=>Q(`Pyramide: rechteckige Grundfläche ${p.a} cm × ${p.b} cm, senkrechte Höhe ${p.c} cm. Berechne V in cm³.`,p.a*p.b*p.c/3,`V = ${p.a}·${p.b}·${p.c}/3`,'Nutze die senkrechte Höhe, nicht eine Seitenkante.'),(p,z)=>close(3*z/(p.a*p.b),p.c));
add('kegel-mantel','Kegel: Mantelfläche',2,'G','Für den Kegelmantel gilt M = πrs. Die Mantellinie s ist nicht die senkrechte Höhe.',p=>Q(`Gerader Kegel: Radius ${p.a} cm, Mantellinie ${p.a+p.b} cm. Berechne die Mantelfläche in cm².`,Math.PI*p.a*(p.a+p.b),`M = π·${p.a}·${p.a+p.b}`,'Die Grundfläche gehört nicht zur Mantelfläche.',{round:2}),(p,z)=>close(z/(Math.PI*p.a),p.a+p.b));
add('kegel-oberflaeche','Kegel: Oberfläche aus r und h',3,'G','Bestimme s = √(r²+h²). Die gesamte Oberfläche ist Grundfläche plus Mantel: O = πr² + πrs.',p=>Q(`Gerader Kegel: r = ${p.a} cm, h = ${p.b} cm. Berechne die gesamte Oberfläche in cm².`,Math.PI*p.a*(p.a+Math.hypot(p.a,p.b)),`s = √(${p.a}²+${p.b}²); O = π·${p.a}² + π·${p.a}·s`,'Verwende zuerst Pythagoras im Schnittdreieck.',{round:2}),(p,z)=>close((z/(Math.PI*p.a)-p.a)**2,p.a*p.a+p.b*p.b));
add('zusammengesetzt','Zylinder und Halbkugel',3,'G','Nicht überlappende Teilvolumina werden addiert. Eine Halbkugel hat das halbe Kugelvolumen.',p=>Q(`Ein Körper besteht aus einem Zylinder (r = ${p.a} cm, h = ${p.b} cm) und einer aufgesetzten Halbkugel mit gleichem Radius. Berechne das Gesamtvolumen in cm³.`,Math.PI*p.a*p.a*p.b+2*Math.PI*p.a**3/3,`V = π·${p.a}²·${p.b} + 2π·${p.a}³/3`,'Die beiden Teilkörper überlappen sich nicht.',{round:2}),(p,z)=>close((z-Math.PI*p.a*p.a*p.b)*3/(2*Math.PI),p.a**3));
add('nano-meter','Nano in Meter',2,'G','Nano bedeutet 10⁻⁹. Beim Umrechnen bleibt die physikalische Länge gleich.',p=>Q(`Wandle ${(p.a*10+p.c)*100} Nanometer in Meter um.`,(p.a*10+p.c)*100e-9,`${(p.a*10+p.c)*100} · 10⁻⁹ m`,'Du darfst wissenschaftlich schreiben, etwa 1e-6.'),(p,z)=>close(z*1e9,(p.a*10+p.c)*100));
topic='wachstum';
add('wachstum-faktor','Wachstumsfaktor',1,'G','Bei p % Zunahme lautet der Faktor q = 1 + p/100. Der Anfangsbestand bleibt darin enthalten.',p=>Q(`Ein Bestand wächst je Schritt um ${p.a+p.c} %. Welchen Faktor q verwendet N(n) = N₀·qⁿ?`,1+(p.a+p.c)/100,`q = 1 + ${p.a+p.c}/100`,'100 % des alten Bestands plus die Zunahme.'),(p,z)=>close((z-1)*100,p.a+p.c));
add('zerfall-faktor','Abnahmefaktor',1,'G','Bei p % Abnahme bleibt der Anteil 1 − p/100 übrig.',p=>Q(`Ein Bestand nimmt je Schritt um ${p.a+p.c} % ab. Bestimme den Faktor q.`,1-(p.a+p.c)/100,`q = 1 − ${p.a+p.c}/100`,'Der Faktor muss zwischen 0 und 1 liegen.'),(p,z)=>close((1-z)*100,p.a+p.c));
add('wachstum-bestand','Bestand nach ganzen Schritten',2,'G','Multipliziere bei jedem ganzen Schritt mit demselben Faktor: N(n) = N₀·qⁿ.',p=>Q(`Modell: N(n) = ${p.a*100}·${f(1+p.b/100)}ⁿ. Berechne N(${p.k}).`,p.a*100*(1+p.b/100)**p.k,`N(${p.k}) = ${p.a*100}·${f(1+p.b/100)}^${p.k}`,'Nicht die prozentuale Zunahme einfach mit n multiplizieren.',{round:2,graph:{kind:'growth',initial:p.a*100,q:1+p.b/100}}),(p,z)=>{for(let i=0;i<p.k;i++)z/=1+p.b/100;return close(z,p.a*100);});
add('halbwert','Halbierung in Schritten',2,'G','Nach jeder Halbwertszeit bleibt die Hälfte des vorherigen Bestands. Verwende den Faktor 1/2.',p=>Q(`Ein Modellbestand startet bei ${p.a*100}. Nach jeder Stunde halbiert er sich. Wie groß ist er nach ${p.n} Stunden?`,p.a*100/2**p.n,`${p.a*100}·(1/2)^${p.n}`,'Die Halbierung wird auf den jeweils verbleibenden Bestand angewendet.'),(p,z)=>close(z*2**p.n,p.a*100));
add('anfangsbestand','Anfangsbestand rekonstruieren',3,'G','Mache die wiederholte Multiplikation rückgängig: N₀ = N(n)/qⁿ.',p=>Q(`Ein Bestand verdoppelt sich je Schritt. Nach ${p.n} Schritten sind es ${p.a*2**p.n}. Wie groß war N₀?`,p.a,`N₀ = ${p.a*2**p.n}/2^${p.n}`,'Teile für jeden Schritt einmal durch 2.'),(p,z)=>close(z*2**p.n,p.a*2**p.n));
add('sinus-amplitude','Sinus: Amplitude',1,'G','Die Amplitude ist der Betrag des Vorfaktors a in y = a·sin(bx). Sie ist immer nichtnegativ.',p=>Q(`Die Schwingung lautet y = −${p.a+p.c}·sin(${p.k}x). Wie groß ist ihre Amplitude?`,p.a+p.c,`Amplitude = |−${p.a+p.c}|`,'Das Minus spiegelt die Schwingung, ändert aber nicht ihre Höhe.'),(p,z)=>z>=0&&close(z*z,(p.a+p.c)**2));
add('sinus-periode','Sinus: Periode im Gradmaß',2,'G','Im Gradmaß ist die Periode von sin(bx) gleich 360°/|b|.',p=>Q(`x wird in Grad gemessen. Bestimme die kleinste positive Periode von y = ${p.a}·sin(${p.b+p.c}x), in Grad.`,360/(p.b+p.c),`T = 360°/${p.b+p.c}`,'Der innere Winkel muss um 360° zunehmen.'),(p,z)=>close(z*(p.b+p.c),360));
add('sinus-wert','Sinus: Funktionswert',2,'G','Setze zuerst x in den inneren Winkel ein. Berechne danach den Sinus und multipliziere mit a.',p=>Q(`f(x) = ${p.a}·sin(${p.k}x), Winkel im Gradmaß. Berechne f(${p.t}).`,p.a*sin(p.k*p.t),`${p.a}·sin(${p.k*p.t}°)`,'Achte auf das Gradmaß auch bei Winkeln über 90°.',{round:2,graph:{kind:'sine',a:p.a,b:p.k}}),(p,z)=>close(z/p.a,sin(p.k*p.t)));
topic='zufall';
add('laplace','Laplace-Wahrscheinlichkeit',1,'E/F · Wiederholung','Bei gleich wahrscheinlichen Ergebnissen gilt P = günstige / alle Ergebnisse.',p=>Q(`In einer Urne liegen ${p.a} rote und ${p.b} blaue gleichartige Kugeln. Eine wird zufällig gezogen. Wie groß ist P(rot)?`,p.a/(p.a+p.b),`${p.a}/(${p.a}+${p.b})`,'Gib einen Anteil zwischen 0 und 1 an, keinen Prozentwert.'),(p,z)=>close(z*(p.a+p.b),p.a));
add('zuruecklegen','Zweimal rot mit Zurücklegen',2,'G','Mit Zurücklegen bleiben die Anzahlen gleich. Multipliziere die Wahrscheinlichkeiten entlang des Pfads.',p=>Q(`Urne: ${p.a} rote, ${p.b} blaue Kugeln. Zweimal ziehen MIT Zurücklegen. Wie groß ist P(zweimal rot)?`,(p.a/(p.a+p.b))**2,`(${p.a}/${p.a+p.b})·(${p.a}/${p.a+p.b})`,'Nach dem Zurücklegen ist die Urne unverändert.'),(p,z)=>close(z*(p.a+p.b)**2,p.a*p.a));
add('ohne-zuruecklegen','Zweimal rot ohne Zurücklegen',2,'G','Ohne Zurücklegen fehlt beim zweiten Zug eine Kugel; auf diesem Pfad fehlt eine rote Kugel.',p=>Q(`Urne: ${p.a} rote, ${p.b} blaue Kugeln. Zweimal ziehen OHNE Zurücklegen. Berechne P(zweimal rot).`,p.a/(p.a+p.b)*(p.a-1)/(p.a+p.b-1),`${p.a}/${p.a+p.b} · ${p.a-1}/${p.a+p.b-1}`,'Verringere beim zweiten Zug Zähler und Nenner um 1.'),(p,z)=>close(z*(p.a+p.b)*(p.a+p.b-1),p.a*(p.a-1)));
add('verschieden','Genau eine rote Kugel',3,'G','Genau eine rote Kugel entsteht über zwei getrennte Pfade: rot–blau oder blau–rot.',p=>Q(`Urne: ${p.a} rote, ${p.b} blaue Kugeln. Zweimal MIT Zurücklegen ziehen. Berechne P(genau einmal rot).`,2*p.a*p.b/(p.a+p.b)**2,`2 · ${p.a}/${p.a+p.b} · ${p.b}/${p.a+p.b}`,'Beide Reihenfolgen zählen.'),(p,z)=>close(z*(p.a+p.b)**2,p.a*p.b+p.b*p.a));
add('mindestens','Mindestens einmal rot',3,'G','Das Gegenereignis zu „mindestens einmal rot“ ist „keinmal rot“, also zweimal blau.',p=>Q(`Urne: ${p.a} rote, ${p.b} blaue Kugeln. Zweimal MIT Zurücklegen ziehen. Bestimme P(mindestens einmal rot).`,1-(p.b/(p.a+p.b))**2,`1 − (${p.b}/${p.a+p.b})²`,'Ziehe die Wahrscheinlichkeit für zweimal blau von 1 ab.'),(p,z)=>close(z*(p.a+p.b)**2,p.a*p.a+2*p.a*p.b));
add('pfad-drei','Dreistufiger Pfad',3,'G','Auch bei drei Stufen werden die Pfadwahrscheinlichkeiten multipliziert; eine feste Reihenfolge ist nur ein Pfad.',p=>Q(`Urne: ${p.a} rote, ${p.b} blaue Kugeln. Dreimal MIT Zurücklegen ziehen. Berechne P(rot, blau, rot in genau dieser Reihenfolge).`,p.a*p.b*p.a/(p.a+p.b)**3,`${p.a}/${p.a+p.b} · ${p.b}/${p.a+p.b} · ${p.a}/${p.a+p.b}`,'Nicht mit drei multiplizieren: Die Reihenfolge ist fest.'),(p,z)=>close(z*(p.a+p.b)**3,p.a*p.b*p.a));
add('kombination','Produktregel: Möglichkeiten',1,'E/F · Wiederholung','Für jede Wahl im ersten Schritt stehen alle Möglichkeiten des nächsten Schritts offen. Multipliziere die Anzahlen.',p=>Q(`Ein Menü besteht aus einer von ${p.a} Vorspeisen, einer von ${p.b} Hauptspeisen und einem von ${p.c} Desserts. Wie viele verschiedene Menüs gibt es?`,p.a*p.b*p.c,`${p.a} · ${p.b} · ${p.c}`,'Jede Kombination der drei Gänge ist erlaubt.'),(p,z)=>{let count=0;for(let i=0;i<p.a;i++)for(let j=0;j<p.b;j++)for(let k=0;k<p.c;k++)count++;return z===count;});
add('erwartete-haeufigkeit','Erwartete Häufigkeit',2,'E/F · Vertiefung','Die erwartete Anzahl beträgt Versuchszahl · Wahrscheinlichkeit. Das ist keine Garantie für eine konkrete Versuchsreihe.',p=>Q(`Ein Ereignis hat P = ${p.a}/${p.a+p.b}. Wie oft erwartet man es bei ${(p.a+p.b)*p.c} unabhängigen Versuchen im Mittel?`,p.a*p.c,`${(p.a+p.b)*p.c} · ${p.a}/${p.a+p.b}`,'Gesucht ist die durchschnittlich erwartete Anzahl.'),(p,z)=>close(z/((p.a+p.b)*p.c),p.a/(p.a+p.b)));
topic='daten';
add('mittelwert','Arithmetisches Mittel',1,'E/F · Wiederholung','Addiere alle Werte und teile durch ihre Anzahl. Jeder Wert zählt gleich viel.',p=>Q(`Berechne das arithmetische Mittel der Werte ${p.a}; ${p.b}; ${p.c}; ${p.x}.`,(p.a+p.b+p.c+p.x)/4,`(${p.a}+${p.b}+${p.c}+(${p.x}))/4`,'Es gibt vier Werte; auch ein negativer Wert zählt mit.'),(p,z)=>close(4*z-p.a-p.b-p.c,p.x));
add('median','Median bei gerader Anzahl',2,'E/F · Wiederholung','Sortiere zuerst. Bei gerader Anzahl ist der Median der Mittelwert der beiden mittleren Werte.',p=>Q(`Bestimme den Median der Werte ${p.a}; ${p.b}; ${p.c}; ${p.x}.`,[p.a,p.b,p.c,p.x].sort((a,b)=>a-b).slice(1,3).reduce((a,b)=>a+b)/2,`Sortiert: ${[p.a,p.b,p.c,p.x].sort((a,b)=>a-b).join('; ')}. Mittel der beiden inneren Werte bilden.`,'Nicht den Mittelwert aller vier Werte nehmen.'),(p,z)=>close(2*z,p.a+p.b+p.c+p.x-Math.min(p.a,p.b,p.c,p.x)-Math.max(p.a,p.b,p.c,p.x)));
add('spannweite','Spannweite',1,'E/F · Wiederholung','Die Spannweite ist größter Wert minus kleinster Wert; sie ist nie negativ.',p=>Q(`Bestimme die Spannweite der Werte ${p.a}; ${p.b}; ${p.c}; ${p.x}.`,Math.max(p.a,p.b,p.c,p.x)-Math.min(p.a,p.b,p.c,p.x),`Maximum − Minimum = ${Math.max(p.a,p.b,p.c,p.x)} − (${Math.min(p.a,p.b,p.c,p.x)})`,'Suche zuerst die beiden Extremwerte.'),(p,z)=>{const v=[p.a,p.b,p.c,p.x].sort((a,b)=>a-b);return close(v[0]+z,v[3]);});
add('gewichtetes-mittel','Mittelwert aus Häufigkeiten',2,'E/F · Vertiefung','Multipliziere jeden Wert mit seiner Häufigkeit, addiere und teile durch die Gesamtzahl.',p=>Q(`Eine Messung liefert ${p.a}-mal den Wert 2 und ${p.b}-mal den Wert 5. Berechne den Mittelwert.`,(2*p.a+5*p.b)/(p.a+p.b),`(2·${p.a}+5·${p.b})/(${p.a}+${p.b})`,'Die beiden Werte treten nicht unbedingt gleich oft auf.'),(p,z)=>{const v=[...Array(p.a).fill(2),...Array(p.b).fill(5)];return close(z*v.length,v.reduce((a,b)=>a+b));});
add('relative-haeufigkeit','Relative Häufigkeit in Prozent',1,'E/F · Wiederholung','Relative Häufigkeit = Anzahl / Gesamtzahl. Für Prozent mit 100 multiplizieren.',p=>Q(`Von ${p.a+p.b} Beobachtungen entfallen ${p.a} auf Kategorie A. Gib die relative Häufigkeit in Prozent an (nur Zahl).`,100*p.a/(p.a+p.b),`${p.a}/${p.a+p.b} · 100`,'Hier ist ausdrücklich die Prozentzahl gesucht.',{round:2}),(p,z)=>close(z/100*(p.a+p.b),p.a));
add('diagramm-manipulation','Verkürzte Diagrammachse',3,'G','Bei einer verkürzten Achse ist die Balkenhöhe Wert minus Achsenbeginn. Das Verhältnis der sichtbaren Höhen ist nicht das Verhältnis der Werte.',p=>Q(`Zwei Balken zeigen ${p.a+20} und ${p.a+p.b+20}. Die y-Achse beginnt bei 20. Wie groß ist das Verhältnis sichtbare Höhe des zweiten Balkens / sichtbare Höhe des ersten?`,(p.a+p.b)/p.a,`(${p.a+p.b+20}−20)/(${p.a+20}−20)`,'Ziehe bei beiden Balken den Achsenbeginn ab. So kann der Unterschied übertrieben wirken.',{bars:{values:[p.a+20,p.a+p.b+20],base:20}}),(p,z)=>close(z*p.a,p.a+p.b));
add('trend','Trend: mittlere tägliche Änderung',2,'G','Teile die gesamte Änderung durch die Zahl der Zeitintervalle. Ein Trend beweist keine Ursache.',p=>Q(`Eine Zählung steigt in ${p.k} Tagen von ${p.a*10} auf ${p.a*10+p.b}. Wie groß ist die mittlere tägliche Änderung?`,p.b/p.k,`(${p.a*10+p.b} − ${p.a*10})/${p.k}`,'Gezählt werden die verstrichenen Tage, nicht die Messpunkte.'),(p,z)=>close(z*p.k+p.a*10,p.a*10+p.b));
add('stichprobe','Stichprobe: fehlende Gruppe',3,'G','Eine Stichprobe sollte die Zielgruppe abbilden. Wird eine ganze Gruppe ausgelassen, kann die Aussage verzerrt sein.',p=>Q(`Eine Schule hat ${p.a*10} Mitglieder in der Sport-AG und ${p.b*10} andere Lernende. Nur die Sport-AG wird zum Sportinteresse befragt. Wie viel Prozent der Schule bleiben unbefragt (nur Zahl)?`,100*p.b/(p.a+p.b),`${p.b*10}/${(p.a+p.b)*10} · 100`,'Die Sport-AG allein ist keine repräsentative Auswahl der Schule.',{round:2}),(p,z)=>close((1-z/100)*(p.a+p.b),p.a));
export function generate(id,seed){
 const type=types.find(t=>t.id===id);if(!type)throw new Error('Unbekannter Aufgabentyp');
 const r=rng(seed),i=(lo,hi)=>lo+Math.floor(r()*(hi-lo+1));
 const p={a:i(2,9),b:i(2,9),c:i(1,8),x:i(-5,5),k:i(2,4),n:i(2,5),t:i(4,14)*5,u:i(4,12)*5};
 const q={...type.build(p),id,seed:seed>>>0,p,rule:type.rule,title:type.title,topic:type.topic,level:type.level,scope:type.scope};
 q.steps.push(`Ergebnis: ${answerText(q)}${q.round!==undefined?' (auf zwei Nachkommastellen gerundet)':''}.`);
 return q;
}
