// Eigenständige Lehrtexte; IDs stammen unverändert aus catalog.js.
import {stories} from './lesson-story.js';
const foundations = [
{
 id:'zahlen',
 recall:'Ein Bruch a/b bedeutet a geteilt durch b; b darf nicht null sein. Zähler und Nenner mit derselben von null verschiedenen Zahl zu multiplizieren ändert seinen Wert nicht: 1/2 = 2/4. Beim Multiplizieren zweier Brüche multipliziert man Zähler mit Zähler und Nenner mit Nenner. Ein negativer und ein positiver Faktor ergeben ein negatives Produkt. Klammern gehen vor Potenzen, Potenzen vor Punktrechnung und diese vor Strichrechnung.',
 concepts:[['Basis und Exponent','In 3⁴ ist 3 die Basis und 4 der Exponent: vier Faktoren 3 ergeben 81. Der Exponent sagt nicht, dass man 3 mit 4 multipliziert.'],['Kehrwert','Der Kehrwert von a/b ist b/a, sofern a und b nicht null sind. Ihr Produkt ist 1. Auch 3⁻² ist ein Kehrwert: 1/3².'],['Quadratwurzel und reelle Zahl','√N bezeichnet für N ≥ 0 die nichtnegative Zahl, deren Quadrat N ergibt. Manche Wurzeln sind keine Brüche, etwa √2. Rationale und irrationale Zahlen bilden zusammen die reellen Zahlen.']],
 reasoning:[
 "Beim Banner verändert sich nicht die Größe eines Viertels, sondern die Anzahl der benötigten Viertel. Drei und zwei ergeben fünf: 3/4+2/4 = 5/4. Der Nenner ist der Name der Stückgröße, deshalb bleibt er stehen. Sind die Stücke verschieden groß, musst du sie vor dem Zählen auf dieselbe Größe bringen, etwa 1/2 = 2/4. Das erklärt auch, warum die Bruchdivision eine andere Frage beantwortet. Bei (3/4):(1/4) fragst du, wie oft ein Viertel in drei Viertel passt: dreimal. Multiplizieren mit dem Kehrwert liefert genau diese Anzahl. Negative Brüche in den Übungen sind dagegen Zahlen oder Bilanzänderungen, kein negativer Stoff.",
 "Die Abkürzung 3²·3³ bedeutet zunächst nichts Geheimnisvolles: Schreibe 3·3 neben 3·3·3, dann siehst du fünf gleiche Faktoren. Beim Teilen kürzt du gemeinsame Faktoren: 3⁵:3² lässt drei Faktoren übrig. Drehe jetzt die Aufgabe um. Bei 3²:3⁵ bleiben drei Faktoren unten im Bruch, also 1/3³. Damit die Regel „Exponenten subtrahieren“ auch auf diesem Rückweg stimmt, heißt diese Zahl 3⁻³. Ebenso muss 3⁰ = 1 sein, denn 3³:3³ = 1. Das Minus beschreibt also eine Position im Nenner, nicht eine negative Menge. Die Basis muss bei solchen Kehrwerten von null verschieden sein.",
 "Bei (3²)³ wird nicht einfach ein weiterer Faktor 3 angehängt. Hier werden drei ganze Zweierblöcke multipliziert: (3·3)·(3·3)·(3·3). Zähle nach: Es sind sechs Faktoren, daher 3⁶. Vergleiche das mit 3²+3³. Dort addierst du zwei fertige Zahlen; daraus wird keine einzige Kette gleicher Faktoren. Für eure Materialliste lohnt deshalb der Blick auf das Rechenzeichen vor jedem Potenzgesetz. Die wissenschaftliche Schreibweise benutzt Zehnerpotenzen als Größenstaffel. In der normierten Schreibweise einer positiven Zahl liegt der Vorfaktor zwischen 1 einschließlich und 10 ausschließlich. Beim Verschieben des Kommas muss sich die Zehnerpotenz so ändern, dass die Zahl gleich bleibt.",
 "Für die quadratische Fläche probierst du nicht beliebige Seitenlängen, sondern bekannte Quadrate. Eine Seite 3 ergibt Fläche 9, eine Seite 4 Fläche 16. Die gesuchte Fläche 11 liegt dazwischen, also 3 < √11 < 4. Das funktioniert, weil längere nichtnegative Seiten größere Quadratflächen ergeben. √11 ist der exakte Name der gesuchten Länge, auch wenn keine endliche Dezimalzahl dafür ausreicht. Die untere ganze Grenze 3 beantwortet die Einschachtelungsaufgabe, aber nicht die Frage nach der exakten Seite. Zur Planung könnt ihr den Bereich später enger machen; schon jetzt weißt du, dass ein Vorschlag von 5 Einheiten unmöglich passt."
 ],
 mistakes:'Ein Minus im Exponenten ist kein negatives Ergebnis. 3⁻² = 1/9, nicht −9. Beim Teilen nur den zweiten Bruch umdrehen. Bei Potenzgesetzen zuerst prüfen: gleiche Basis und wirklich ein Produkt oder Quotient? Kontrolliere kleine Zahlen durch Rückmultiplikation und Zehnerpotenzen durch die Größenordnung.',
 checks:[['Warum ist 5⁻² positiv?','Es ist der Kehrwert 1/25 einer positiven Zahl; das Minus beschreibt die Kehrwertbildung.'],['Zwischen welchen ganzen Zahlen liegt √30?','Zwischen 5 und 6, denn 25 < 30 < 36. Die größte ganze Zahl darunter ist 5.'],['Ist (2³)² dasselbe wie 2³ · 2²?','Nein. Links stehen sechs Faktoren 2 (64), rechts fünf (32).']],
},
{
 id:'gleichungen',
 recall:'Eine Variable ist ein Platzhalter für eine Zahl. 3x bedeutet 3 · x. Eine Klammer wird mit dem Distributivgesetz ausmultipliziert: a(b+c) = ab+ac. Gleichartige Terme lassen sich zusammenfassen, etwa 2x+3x = 5x; x und x² sind dagegen nicht gleichartig. Für negative Zahlen gilt beispielsweise (−5)² = 25, aber −5² = −25. Lies Klammern deshalb sorgfältig.',
 concepts:[['Term, Gleichung, Lösung','Ein Term wie 3x+4 hat allein kein Wahrheitszeichen. Eine Gleichung setzt zwei Terme gleich. Eine Lösung macht nach dem Einsetzen beide Seiten gleich.'],['Äquivalenzumformung','Eine Umformung, die die Lösungsmenge erhält: dieselbe Zahl auf beiden Seiten addieren oder subtrahieren; mit derselben von null verschiedenen Zahl multiplizieren oder durch sie teilen.'],['Faktor und Nullprodukt','Faktoren sind die Teile einer Multiplikation. Ein Produkt reeller Zahlen ist genau dann null, wenn mindestens ein Faktor null ist. Für eine Summe gilt das nicht.']],
 reasoning:[
 "Gehe in der Bilanz 3x+4 = −2 wirklich rückwärts. Ziehe auf beiden Seiten 4 ab: 3x = −6. Teile dann beide Seiten durch 3: x = −2. Warum gerade diese Reihenfolge? Die 4 wurde zuletzt hinzugefügt, also wird sie zuerst entfernt. Die Rechenkette unten zeigt diesen Rückweg. Wichtig ist nicht ein scheinbares „Springen auf die andere Seite“, sondern dass du beide Seiten gleich behandelst. Durch die bekannte Zahl 3 darfst du teilen; durch das unbekannte x nicht einfach, denn es könnte null sein. Prüfe am ursprünglichen Zettel: 3·(−2)+4 = −2. Damit ist die einzelne Korrektur gefunden und die gesamte Bilanz stimmt.",
 "Beschrifte die alte Quadratseite im Entwurf mit x und die Verlängerung mit d. Die neue Fläche ist (x+d)(x+d). Wenn du jede Teilbreite mit jeder Teilhöhe multiplizierst, entstehen vier Stücke: x², dx, dx und d². Die beiden Streifen haben zusammen 2dx; erst damit ist die neue Fläche vollständig. So entsteht (x+d)² = x²+2dx+d². Bei (x−d)(x+d) entstehen stattdessen +dx und −dx, die sich aufheben: x²−d² bleibt. Eine Skizze erklärt das für passende positive Längen. Das Ausmultiplizieren begründet die Identität darüber hinaus für alle reellen x und d. Eine richtige algebraische Probe muss daher nicht selbst einen baubaren Entwurf darstellen.",
 "Für eine Fläche 25 fragt die Gleichung x² = 25 zunächst nur nach Zahlen mit diesem Quadrat. Sowohl 5 als auch −5 erfüllen sie; erst die Zusatzbedingung „Seitenlänge“ lässt −5 weg. Bei Fläche null bleibt rechnerisch nur x = 0, bei x² = −1 keine reelle Lösung. Für andere Gleichungen kann eine Produktform den Blick freimachen: Ein Produkt ist null, sobald mindestens ein Faktor null ist. Möchtest du x²+sx+p in (x+u)(x+v) zerlegen, müssen deshalb zwei Kontrollen stimmen: u+v = s und uv = p. Ausmultiplizieren zeigt dir beide Bedingungen. Die Übungen wählen passende ganzzahlige Faktoren; bei einer beliebigen quadratischen Gleichung muss diese Suche nicht aufgehen.",
 "Bei zwei Abrechnungsbedingungen reicht es nicht, einen Zettel passend zu machen. Betrachte x+y = 2 und x−y = −6. Addiere die linken und die rechten Seiten: 2x = −4, weil y und −y sich aufheben. Daraus folgt x = −2. Setze diesen Wert in die erste Gleichung: −2+y = 2, also y = 4. Jetzt kommen beide Zettel zurück auf den Tisch: −2+4 = 2 und −2−4 = −6. Erst diese doppelte Probe bestätigt das Zahlenpaar. Das Übungsfeld verlangt hier nur x, aber deine eigene Dokumentation sollte y nicht verlieren. Ein kürzeres Antwortformat ist keine kürzere mathematische Bedingung."
 ],
 mistakes:'Nicht nur eine Seite verändern. Nicht (x+5)² mit x²+25 verwechseln. Nicht aus einem Produkt x−3 = 0 UND x+4 = 0 verlangen: Es genügt ODER. Bei mehrfach auftretender gleicher Wurzel die Lösung nur einmal nennen. Alle gefundenen Werte in die ursprüngliche Gleichung einsetzen.',
 checks:[['Darfst du 2x = 0 durch x teilen?','Nicht ohne Fallunterscheidung: x = 0 ist gerade die Lösung und Division durch null ist nicht erlaubt. Teile stattdessen durch 2.'],['Welche Zahl steht vor x in (x+7)²?','14, weil die beiden gemischten Produkte je 7x ergeben.'],['Warum genügt eine Probe nur in der ersten LGS-Gleichung nicht?','Ein Zahlenpaar kann eine Bedingung erfüllen und die andere verletzen; ein System verlangt beide.']],
},
{
 id:'linear',
 recall:'Ein Punkt P(x|y) nennt zuerst die waagerechte, dann die senkrechte Koordinate. Eine Differenz ist Endwert minus Anfangswert und kann negativ sein. Brüche drücken auch Verhältnisse aus. Eine Gleichung ax+b = c löst du durch Subtrahieren von b und Teilen durch a, sofern a ≠ 0. Beim Einsetzen eines negativen x helfen Klammern: 2 · (−2)+4 = 0.',
 concepts:[['Funktion und Funktionswert','Eine Funktion ordnet jedem zulässigen x genau einen Wert y = f(x) zu. Der Graph besteht aus den Punkten (x|f(x)).'],['Steigung m','In f(x) = mx+b gibt m die Änderung von y pro zusätzlicher Einheit x an. Positives m bedeutet Anstieg, negatives m Abnahme. Die Einheit kann beispielsweise Euro je Stunde sein.'],['Achsenabschnitt b und Nullstelle','b = f(0) ist der Schnitt mit der y-Achse. Eine Nullstelle ist ein x-Wert mit f(x) = 0 und liegt auf der x-Achse. Das sind unterschiedliche Angaben.']],
 reasoning:[
 "Im Angebot ist jede zusätzliche Stunde gleich teuer. Schreibe zuerst die Bedeutung auf: x ist die Dauer in Stunden, f(x) der Preis in Euro. Dann lautet die Vorschrift f(x) = 2x+4. Von drei zu vier Stunden steigt sie von 10 auf 12; die Grundgebühr taucht in beiden Preisen auf und verschwindet beim Subtrahieren. Genau das verallgemeinert f(x+Δx)−f(x) = mΔx. Lies Δx als „Änderung von x“ und Δy als „Änderung von y“: Der Quotient Δy/Δx ist der Zuwachs je Einheit, also m. Bilde beide Differenzen in derselben Richtung. Bei Δx = 0 darfst du nicht teilen; eine senkrechte Gerade ist auch keine Funktion der Form y = mx+b.",
 "Angenommen, auf dem Angebotszettel stehen nur Stundenpreis und ein Gesamtpreis. Für drei Stunden sind es 10 Euro bei 2 Euro je Stunde. Der Zeitanteil ist 6 Euro, also bleiben 4 Euro als Grundgebühr. In Buchstaben ist das b = y−mx. Ein bekannter Punkt liefert y und x, die Rate liefert m. Danach hast du die ganze Vorschrift und kannst neue Preise berechnen. Umgekehrt wird die Frage „Welche Dauer gehört zu diesem Preis?“ zur Gleichung. An einer Nullstelle ist der verlangte Funktionswert null. Die abstrakten Übungen dürfen dabei negative Koordinaten liefern. Für einen tatsächlichen Tarif müsstest du anschließend prüfen, ob die Dauer überhaupt zulässig ist.",
 "Wenn zwei Angebote gleich teuer sind, beschreiben sie dieselbe Dauer und denselben Preis. Deshalb setzt du die Terme gleich, nicht etwa ihre Steigungen. Die Gleichung liefert zuerst die Dauer x; Einsetzen liefert danach den gemeinsamen Preis y. Erst zusammen bilden sie den Schnittpunkt. Für die Entscheidung im Team folgt noch eine zweite Frage: Welches Angebot liegt bei einer kürzeren oder längeren zulässigen Dauer darunter? Ein Schnittpunkt bei negativer Dauer beantwortet die reale Ausleihfrage nicht. Haben zwei Geraden dieselbe Steigung, entscheidet die Grundgebühr: verschiedene Grundgebühren ergeben parallele Geraden, gleiche Grundgebühren dieselbe Gerade. Der Generator vermeidet diesen Sonderfall durch unterschiedliche Steigungen.",
 "Das Leihradmodell liefert bei drei Stunden 10 Euro und bei sechs Stunden 16 Euro. Es setzt voraus, dass die 4 Euro genau einmal anfallen und jede Stunde 2 Euro kostet. Haltet diese Annahmen neben der Formel fest. Bei einem Tageshöchstpreis würde die Gerade irgendwann nicht mehr passen; bei voll berechneten angefangenen Stunden wären Zwischenwerte anders zu behandeln. Eine negative Dauer ist im Graphen einsetzbar, aber keine Ausleihe. Eine Formel ist daher nicht allein schon ein vollständiges Angebot. Für eure Zeitreserve ist besonders die Steigung nützlich: Eine zusätzliche ganze Stunde erhöht den geplanten Preis um genau 2 Euro, solange das vereinbarte Modell gilt."
 ],
 mistakes:'Steigung ist nicht y/x, außer die Gerade geht durch den Ursprung. Vertausche nicht Δx und Δy. Ein negativer Änderungswert bedeutet Abnahme, nicht eine negative Dauer. Ein Schnittpunkt ist ein Punkt; wenn das Antwortfeld nur x verlangt, darf dort trotzdem nicht das Zahlenpaar stehen.',
 checks:[['Ändert eine höhere Grundgebühr die Steigung?','Nein. Sie ändert b, während der Preis je Einheit m gleich bleibt.'],['Eine Gerade fällt bei Δx = 3 um 6. Welche Steigung hat sie?','m = −6/3 = −2. Das Minus kennzeichnet die Abnahme.'],['Was prüfst du nach einer Schnittpunktrechnung?','Dass beide Funktionsterme beim gefundenen x denselben y-Wert liefern.']],
},
{
 id:'quadratisch',
 recall:'Ein Quadrat ist für reelle Zahlen immer nichtnegativ: (−3)² = 3² = 9. Die Quadratwurzel √9 ist die nichtnegative Zahl 3; die Gleichung x² = 9 hat dennoch zwei Lösungen. Eine Funktion ordnet x einen y-Wert zu. Die Nullstelle ist ein x-Wert mit y = 0. Klammer, Quadrat, Multiplikation und Addition werden in dieser Reihenfolge berechnet.',
 concepts:[['Scheitelform','f(x) = a(x−h)²+k mit a ≠ 0. Der Scheitel liegt bei S(h|k), weil dort x−h = 0 ist.'],['Öffnung und Streckung','a > 0 öffnet nach oben, a < 0 nach unten. Größeres |a| bedeutet bei gleichem Abstand vom Scheitel größere Höhenunterschiede und damit eine schmalere Parabel.'],['Symmetrieachse und Extremwert','Die Gerade x = h ist die Symmetrieachse. Bei a > 0 ist k ein Minimum, bei a < 0 ein Maximum, sofern alle reellen x zugelassen sind.']],
 reasoning:[
 "Fange beim Muster mit y = x² an. Die kleinste Höhe ist null, und sie liegt bei x = 0. Soll diese Mitte nun bei x = 3 liegen, brauchst du in der Klammer etwas, das genau dort null wird: x−3. Deshalb verschiebt (x−3)² nach rechts, obwohl dort ein Minus steht. Mit +4 außerhalb der Klammer wächst anschließend jede Höhe um 4. Der Scheitel von (x−3)²+4 ist also S(3|4). Allgemein macht x = h die Klammer in a(x−h)²+k null. Der Faktor a verändert dann die Höhenunterschiede: positiv nach oben, negativ nach unten. Bei gleichem Abstand bedeutet ein größeres |a| einen größeren Unterschied zum Scheitel, nicht eine seitliche Verschiebung.",
 "Legt eure Markierungen zuerst nach dem Abstand zur Mitte fest. Bei x = 5 ist der Abstand zu 3 gleich +2, bei x = 1 gleich −2. Beide Quadrate sind 4, also liegen beide Punkte auf Höhe 8. In Buchstaben ersetzt du x einmal durch h+d und einmal durch h−d. Es bleiben d² und (−d)², also derselbe Höhenbeitrag. Daraus folgt auch eine praktische Kontrolle: Die beiden x-Koordinaten haben die Summe 2h. Bei einem verschobenen Muster brauchst du deshalb keine ganz neue Wertetabelle für Spiegelpunkte. Liegt ein Punkt schon auf der Achse x = h, wird er allerdings auf sich selbst gespiegelt; einen anderen Punkt gibt es dann nicht.",
 "Eine Bezugslinie auf Höhe null wird nur erreicht, wenn a(x−h)²+k = 0 lösbar ist. Entferne zuerst k und teile durch das von null verschiedene a. Jetzt steht (x−h)² = −k/a. Halte hier an: Ist rechts eine negative Zahl, kann das Quadrat sie nicht erreichen. Bei null gibt es nur x = h. Bei einer positiven Zahl r gibt es zwei Abstände, +√r und −√r, also x = h±√r. Diese Fallentscheidung beschreibt genau, ob euer Entwurf die Linie verfehlt, berührt oder zweimal schneidet. „Keine reelle Lösung“ ist deshalb eine hilfreiche Nachricht über eine unpassende Vorgabe, nicht ein Fehler, den du durch Runden beheben könntest.",
 "Ist die Mitte festgelegt, könnt ihr das Muster immer noch schmaler oder weiter öffnen. Ein zusätzlicher Punkt P außerhalb der Scheitelachse legt fest, welcher Höhenunterschied yP−k zu welchem Abstand xP−h gehört. Setze ihn in yP−k = a(xP−h)² ein und teile durch das Abstandsquadrat: a = (yP−k)/(xP−h)². Ein Punkt auf der Achse wäre hierfür ungeeignet, weil der Nenner null wäre. Der Scheitel selbst fügt keine neue Information über die Öffnung hinzu. Prüfe den berechneten Faktor am Zusatzpunkt, bevor ihr weitere Markierungen übertragt. Dieses Verfahren benutzt die bekannte Scheitelform; es ist nicht automatisch ein Verfahren für jede beliebige quadratische Gleichung."
 ],
 mistakes:'In (x+5)² steht h = −5, nicht 5. Das Minimum ist ein y-Wert, der Scheitel ein Punkt und eine Nullstelle ein x-Wert. Nach dem Wurzelziehen beide Vorzeichen berücksichtigen. Runden erst am Schluss. Bei Sachmodellen kontrollieren, ob der Scheitel überhaupt im erlaubten Bereich liegt.',
 checks:[['Wo liegt der Scheitel von −2(x+3)²+7?','Bei S(−3|7). Wegen a = −2 ist 7 der größte, nicht der kleinste Funktionswert.'],['Wie viele reelle Lösungen hat (x−4)² = −2?','Keine: Kein reelles Quadrat ist negativ.'],['Welche x-Koordinate ist zu x = 8 an x = 3 gespiegelt?','−2. Beide liegen im Abstand 5 von der Symmetrieachse; 8+(−2) = 2 · 3.']],
},
{
 id:'trigonometrie',
 recall:'Die Winkelsumme im Dreieck ist 180°. Ein rechter Winkel misst 90°. Die Fläche ist Grundseite mal zugehörige senkrechte Höhe geteilt durch 2. Seitenlängen sind positiv. Quadrate und Quadratwurzeln machen einander für nichtnegative Zahlen rückgängig. Am Taschenrechner bedeutet DEG Gradmaß; RAD wäre für diese Übungen falsch. Die Umkehrfunktion arctan oder tan⁻¹ ist nicht der Kehrwert 1/tan.',
 concepts:[['Hypotenuse und Katheten','Im rechtwinkligen Dreieck liegt die Hypotenuse gegenüber 90° und ist die längste Seite. Die beiden Seiten am rechten Winkel heißen Katheten.'],['Gegen- und Ankathete','Diese Namen hängen vom gewählten spitzen Winkel α ab. Die Gegenkathete liegt gegenüber α; die Ankathete liegt an α und ist nicht die Hypotenuse.'],['Trigonometrische Verhältnisse','sin α = g/c, cos α = a/c, tan α = g/a. In allgemeinen Dreiecken steht die Seite a gegenüber α, b gegenüber β und c gegenüber γ.']],
 reasoning:[
 "Vergrößere den Lageplan gedanklich auf das Doppelte. Gegenkathete, Ankathete und Hypotenuse werden jeweils doppelt so lang. In einem Quotienten kürzt sich der gemeinsame Faktor 2 weg. Darum hängen sin α = g/c, cos α = a/c und tan α = g/a vom Winkel ab, nicht von der Größe des Plans. Die Namen Gegen- und Ankathete beziehen sich immer auf den markierten spitzen Winkel α. Suche in deiner Skizze zuerst die bekannte und die gesuchte Seite. Wähle dann den Quotienten, der genau diese beiden enthält. Bei bekannter Hypotenuse c folgt etwa g = c·sin α. Der Sinus selbst ist keine Länge; erst die Multiplikation mit c gibt eine Länge.",
 "Für die 3-cm- und 4-cm-Katheten addierst du nicht die Strecken, sondern ihre Quadratflächen: c² = 3²+4² = 25 cm². Die gesuchte Strecke ist die positive Wurzel, also 5 cm. Das passt zur Schätzung zwischen der längsten Kathete und dem Weg über die Ecke. Möchtest du stattdessen aus zwei Katheten einen Winkel bestimmen, liefert ihr Quotient zunächst dessen Tangens. Mit arctan suchst du den dazugehörigen Winkel. tan⁻¹ auf dem Rechner meint hier diese Umkehrfunktion, nicht 1/tan. Stelle DEG ein, damit die Ausgabe in Grad erfolgt. Eine richtige Taste im falschen Winkelmodus kann sonst eine scheinbar präzise, aber unpassende Antwort liefern.",
 "Bei einem nicht rechtwinkligen Gestaltungselement helfen die einfachen Kathetenquotienten nicht unmittelbar. Zeichne eine Höhe ein: Sie zerlegt das Dreieck in rechtwinklige Teile. Dieselbe Höhe lässt sich dann auf zwei Wegen ausdrücken, als b·sin α und als a·sin β. Gleichsetzen und Umstellen ergibt a/sin α = b/sin β. Damit hast du den Sinussatz nicht nur als Merkformel, sondern aus derselben Höhe gewonnen. Beschrifte vor dem Einsetzen die Gegenüberpaare: a gehört zu α, b zu β. In den Übungen sind zwei Winkel und eine passende Gegenseite gegeben; die Winkelsumme lässt einen dritten positiven Winkel zu. Andere Datenlagen können mehrdeutig sein und werden hier nicht behandelt.",
 "Sind zwei Seiten a und b mit Zwischenwinkel γ bekannt, stelle dir b in zwei Richtungen zerlegt vor: entlang a als b·cos γ und senkrecht dazu als b·sin γ. Das Hilfsdreieck liefert c² = (a−b·cos γ)²+(b·sin γ)². Nach dem Ausmultiplizieren lassen sich die beiden Quadratterme mit sin² γ+cos² γ = 1 zusammenfassen. Diese Identität folgt am Einheitskreis aus Pythagoras. Übrig bleibt c² = a²+b²−2ab·cos γ, der Kosinussatz. Bei 90° ist cos γ = 0, und du erkennst Pythagoras wieder. Für den Papierbedarf nutzt du dieselbe senkrechte Höhe anders: A = a·b·sin γ/2. Randlänge und Fläche entstehen aus derselben Skizze, beantworten aber verschiedene Planungsfragen."
 ],
 mistakes:'Pythagoras und die Kathetenquotienten gelten nur im rechtwinkligen Dreieck. Sinus- und Kosinussatz dagegen auch im allgemeinen. Markiere vor der Rechnung Winkel und gegenüberliegende Seiten. Eine Kathete kann nicht länger als die Hypotenuse sein; ein Dreieck muss außerdem die Dreiecksungleichung erfüllen. Runde erst das Endergebnis auf zwei Nachkommastellen.',
 checks:[['Du kennst Ankathete und Winkel, suchst Gegenkathete. Welche Funktion?','Tangens, denn tan α = Gegenkathete/Ankathete.'],['Warum wird der Kosinussatz bei 90° zu Pythagoras?','cos 90° = 0; der Korrekturterm −2ab cos γ fällt weg.'],['Warum genügt für eine Fläche nicht die schräge Seite als Höhe?','Die Flächenformel benötigt eine senkrechte Höhe; aus der schrägen Seite b wird h = b sin γ.']],
},
{
 id:'koerper',
 recall:'Ein Rechteck hat Fläche Länge mal Breite, ein Kreis G = πr². Der Radius r ist die halbe Länge des Durchmessers. Ein Prisma oder Zylinder mit konstanter Grundfläche hat V = G·h. Pythagoras verbindet rechtwinklige Seiten durch a²+b² = c². Zentimeter, Quadratzentimeter und Kubikzentimeter messen unterschiedliche Dinge. Nutze die π-Taste und runde nicht schon π auf 3,14.',
 concepts:[['Volumen und Oberfläche','V misst den gefüllten Raum in cm³. O misst die gesamte äußere Fläche in cm². Eine Mantelfläche M schließt die Grundfläche gerade nicht ein.'],['Senkrechte Höhe und Mantellinie','h steht senkrecht auf der Grundfläche. Beim geraden Kegel läuft die Mantellinie s schräg von der Spitze zum Kreisrand; s² = r²+h².'],['Maßstab und Einheiten','Wächst jede Länge mit Faktor λ, wachsen Flächen mit λ² und Volumina mit λ³. Nano bedeutet 10⁻⁹ einer Grundeinheit, nicht eine neue geometrische Form.']],
 reasoning:[
 "Vergleiche den Kegel mit einem Zylinder desselben Grundkreises und derselben Höhe. Der Zylinder behält nach oben seine Kreisfläche, der Kegel wird enger. Weniger Rauminhalt ist also plausibel; der genaue Faktor ein Drittel folgt daraus allein noch nicht. Er ist ein geometrischer Satz, den man durch Volumenvergleiche beziehungsweise Zerlegungen begründen kann. Für Kegel und Pyramide gilt V = G·h/3. Bei eurem Kegel ist G = π·3², also V = π·9·4/3 = 12π cm³. Die 4 cm messen senkrecht von der Grundfläche zur Spitze. Eine schräge Länge würde einen anderen Körper beschreiben und gehört nicht an diese Stelle. Die Einheit cm³ bestätigt, dass ihr den Innenraum des idealisierten Modells berechnet.",
 "Beim Zuschneiden wird der Kegelmantel flach zu einem Kreissektor. Sein Radius ist die Mantellinie s, denn sie läuft von der Spitze bis zum Rand. Die Bogenlänge muss genau um den Grundkreis passen, also 2πr betragen. Ein voller Kreis mit Radius s hätte Umfang 2πs. Ihr benötigt daher den Anteil r/s dieses Kreises und damit die Fläche (r/s)·πs² = πrs. Beim 3-4-5-Kegel sind das 15π cm². Für einen geschlossenen Boden kommen 9π cm² dazu, insgesamt 24π cm². Wenn s nicht gegeben ist, berechnest du es zuerst mit s² = r²+h². Das Schnittdreieck ist also ein notwendiger Zwischenschritt vom Entwurf zum Papierbedarf.",
 "Bei der Kugel lauten die Formeln O = 4πr² und V = 4πr³/3. Setze gedanklich 2r statt r ein: In der Fläche kommt die 2 zweimal, im Volumen dreimal als Faktor vor. Darum vervierfacht sich die Hülle, während der Raum achtmal so groß wird. Die Formel für die Kugelfläche bedeutet nicht, dass vier flache Kreise eine verzerrungsfreie Papierhülle ergeben. Für das Volumen hilft ein Vergleich: Eine Halbkugel und ein passender Zylinder minus Kegel haben in jeder gleichen Höhe gleich große Querschnitte. Das Cavalieri-Prinzip erlaubt daraus den Volumenvergleich πr³−πr³/3 = 2πr³/3. Die ganze Kugel hat das Doppelte. Das ist eine Begründung über Querschnitte, nicht bloß über das Aussehen der Silhouette.",
 "Ein Ausstellungsmodell aus Zylinder und Halbkugel lässt sich gedanklich an ihrer Kontaktfläche trennen. Für den Rauminhalt addierst du die beiden nicht überlappenden Teile. Für die äußere Hülle wäre dieselbe ungeprüfte Addition falsch: Die gemeinsame Fläche liegt innen und soll nicht als äußeres Papier doppelt mitgezählt werden. Schreibe daher „Volumen“ oder „Oberfläche“ schon vor die Rechnung. Dieselbe Sorgfalt braucht die ergänzende Nano-Übung. 1 nm = 10⁻⁹ m ändert die Einheit einer Länge, nicht die Länge selbst. Für Flächeneinheiten müsstest du einen Längenfaktor quadrieren, für Volumeneinheiten kubieren. Die Aufgabe hier verlangt nur eine Länge, also genau einen Umrechnungsfaktor."
 ],
 mistakes:'Nicht Radius und Durchmesser vertauschen: Ein verdoppelter Radius vervierfacht die Fläche und verachtfacht das Volumen. Beim Kegel h nicht für s einsetzen. Mantel und gesamte Oberfläche unterscheiden. Jede Formel mit Einheiten prüfen: r²h liefert Länge³, rs liefert Länge². Kleine Längen in Metern dürfen keinesfalls auf null „gerundet“ werden.',
 checks:[['Wie verändert sich ein Kugelvolumen bei doppeltem Radius?','Es wird achtmal so groß, weil (2r)³ = 8r³.'],['Warum ist die Kegelmantellinie länger als die Höhe?','Sie ist die Hypotenuse des Schnittdreiecks: s = √(r²+h²) > h für r > 0.'],['Darf man bei zwei verbundenen Körpern alle Oberflächen einfach addieren?','Nein. Gemeinsame Innenflächen gehören nicht zur äußeren Oberfläche. Teilvolumina ohne Überlappung darf man addieren.']],
},
{
 id:'wachstum',
 recall:'Prozent bedeutet Hundertstel: 12 % = 0,12. Nach einer Zunahme bleibt der alte Bestand erhalten und der Zuwachs kommt hinzu. Eine Potenz qⁿ bedeutet n gleiche Faktoren q. Division macht Multiplikation rückgängig. Im Gradmaß entspricht eine volle Umdrehung 360°. Der Sinus liegt zwischen −1 und 1 und wiederholt sich nach einer vollen Umdrehung.',
 concepts:[['Anfangsbestand N₀ und Faktor q','Im diskreten Modell N(n) = N₀·qⁿ ist n eine ganze nichtnegative Schrittzahl. q ist das Verhältnis zweier aufeinanderfolgender Bestände, nicht die absolute Differenz.'],['Zunahme, Zerfall, Halbwertszeit','q > 1 bedeutet Zunahme; 0 < q < 1 Abnahme. Bei jeder Halbwertszeit bleibt die Hälfte. q = 1 beschreibt einen konstanten Bestand.'],['Amplitude und Periode','Bei y = a sin(bx) ist |a| der maximale Abstand von der Mittellinie 0. Für b ≠ 0 beträgt die kleinste positive Periode im Gradmaß T = 360°/|b|.']],
 reasoning:[
 "Für eure Modellkennzahl ergibt der erste Schritt 300+0,04·300 = 312. Im zweiten Schritt steht an beiden Stellen der neue Bestand: 312+0,04·312 = 324,48. Statt immer zwei Terme zu schreiben, klammerst du den Bestand aus: N+(p/100)N = N(1+p/100). Der gemeinsame Faktor ist q = 1+p/100. Zweimal anwenden bedeutet N₀·q·q, nach n Schritten also N₀·qⁿ. Beim Verlust eines Anteils steht entsprechend q = 1−p/100. Das Vergleichsbild unten zeigt, wann sich diese Rechnung von einem festen Zuwachs unterscheidet. Entscheidend ist die wiederholt neue Bezugsgröße. Das Modell setzt denselben relativen Anteil je gleich langem Schritt voraus; für echte Entwicklungen müsstet ihr diese Annahme erst begründen.",
 "Verfolge eine Halbierung ohne Formel: Nach einem Schritt bleibt die Hälfte, nach zwei Schritten die Hälfte dieser Hälfte, also ein Viertel. Es wird nicht zweimal die Hälfte des Anfangswerts abgezogen. Allgemein bleibt bei positivem Anfangswert nach endlich vielen solchen Schritten immer etwas Positives übrig. Kennt das Team nur einen Endbestand, muss es jeden Veränderungsschritt rückgängig machen: N₀ = N(n)/qⁿ. Durch einmaliges Teilen durch q kommst du auch nur einen Schritt zurück. Prüfe deshalb das Ergebnis anschließend vorwärts. Verdopplung und Halbierung sind besonders gut überschaubare Beispiele. Eine allgemeine unbekannte Schrittzahl mithilfe von Logarithmen zu bestimmen gehört nicht zu diesem Kapitel.",
 "Für die Bildschirmgrafik hilft statt eines wachsenden Bestands ein Punkt auf dem Einheitskreis. Seine senkrechte Koordinate ist der Sinus des Drehwinkels: bei 90° oben bei 1, bei 180° auf Höhe null, bei 270° unten bei −1 und bei 360° wieder bei null. Der Punkt dreht weiter, die Höhen wiederholen sich. Multiplizierst du sie mit a, ändern sich die Abstände zur Mittellinie. Ein negatives a spiegelt die Kurve, macht den Abstand aber nicht negativ. Die Amplitude ist |a| und nur die halbe Entfernung zwischen tiefster und höchster Stelle. Für eure Grafik beschreibt ein negativer Wert die andere Seite der Mittellinie, keine negative Größe des Bildschirms.",
 "Bei y = a·sin(bx) verändert b, wie schnell der innere Winkel beim Weitergehen von x wächst. Soll die Kurve nach einer Eingabeänderung T wieder dieselbe Lage erreichen, muss sich dieser Winkel um eine volle Umdrehung ändern: |b|·T = 360°. Daraus folgt T = 360°/|b|. Der äußere Faktor a beeinflusst diese Wiederholungsweite nicht, solange a nicht null ist. Die Übungen verwenden von null verschiedene Faktoren. Rechne bei einem Funktionswert in derselben Reihenfolge: bx bilden, im Gradmaß den Sinus nehmen, danach mit a multiplizieren. Im Wachstumsmodell zählst du dagegen ganze Schritte. Verwechsle diese Eingaben nicht: Eine Periode in Grad sagt ohne zusätzliche Zeitzuordnung noch nichts über Sekunden."
 ],
 mistakes:'10 % Wachstum bedeutet q = 1,10, nicht q = 0,10 oder 10. Verwechsle relative mit absoluter Änderung nicht. Bei Sinus ist das Minus vor a keine negative Amplitude; b ist nicht die Periode. Nutze DEG, auch wenn bx größer als 90° ist. Modelle sind Annahmen, keine Garantie realer unbegrenzter Zunahme.',
 checks:[['Wie viel bleibt nach zwei Halbierungen?','Ein Viertel des Anfangsbestands: (1/2)² = 1/4.'],['Welche Periode hat 4 sin(3x) im Gradmaß?','120°, weil sich der innere Winkel dann um 360° ändert.'],['Ist das Wachstum bei konstantem q auch jedes Mal absolut gleich groß?','Nein, außer in Sonderfällen wie q = 1. Der Zuwachs hängt vom aktuellen Bestand ab.']],
},
{
 id:'zufall',
 recall:'Ein Anteil günstige/alle liegt zwischen 0 und 1; 1/4 entspricht 25 %. Brüche werden durch Zähler mal Zähler und Nenner mal Nenner multipliziert. Getrennte Anteile desselben Ganzen dürfen addiert werden. Alle möglichen Ergebnisse zusammen haben Wahrscheinlichkeit 1. Ein Ereignis kann aus mehreren Ergebnissen bestehen: „genau eine rote Kugel“ enthält rot–blau und blau–rot.',
 concepts:[['Laplace-Modell','Günstige Ergebnisse geteilt durch alle Ergebnisse gilt, wenn die einzelnen Ergebnisse gleich wahrscheinlich sind. Bei gleichartigen, gut gemischten Kugeln sind die Kugeln die gleich wahrscheinlichen Ergebnisse, nicht automatisch die Farben.'],['Pfad- und Summenregel','Ein vollständiger Weg durch einen Baum hat die Wahrscheinlichkeit als Produkt seiner Zweigwahrscheinlichkeiten. Für mehrere einander ausschließende passende Pfade werden diese Produkte addiert.'],['Gegenereignis und Erwartung','Das Gegenereignis enthält genau alle nicht passenden Ergebnisse. P(E) = 1−P(nicht E). Die erwartete Häufigkeit nP(E) ist ein langfristiger Mittelwert, keine zugesagte Trefferzahl.']],
 reasoning:[
 "Stelle dir viele vergleichbare Ziehungen mit den drei roten und vier blauen Kugeln vor. Im Modell führt der Anteil 3/7 zunächst zum roten Zweig. Innerhalb dieses Anteils führt mit Zurücklegen erneut der Anteil 3/7 zu Rot. Ein Anteil eines Anteils entsteht durch Multiplizieren, also P(RR) = (3/7)·(3/7) = 9/49. Du zählst nicht zwei unabhängige Erfolge zusammen, sondern verlangst beide im selben Ablauf. Erst vollständige, einander ausschließende Pfade werden addiert. Die Zweige bilden ein Modell, keine Zusage bestimmter Trefferzahlen. Damit es zur beschriebenen Aktion passt, müssen die Kugeln gleichartig und gut gemischt sein; die zwei Farben selbst sind nicht gleich wahrscheinlich.",
 "Lies für den zweiten Zug die Urne nach dem ersten Zug neu ab. Ohne Zurücklegen bleiben nach Rot zwei rote und vier blaue Kugeln, also sechs insgesamt. Der RR-Pfad hat dann (3/7)·(2/6) = 1/7. Nach Blau wären dagegen drei rote und drei blaue übrig. Darum können die Zweige derselben Baumstufe verschiedene Brüche tragen. Die kleinere Chance auf RR hat hier einen nachvollziehbaren Grund: Der erste rote Zug verbraucht eine rote Kugel. Mit Zurücklegen und erneutem Mischen stellt ihr den ursprünglichen Bestand wieder her; dann ist der zweite Zug im Modell unabhängig vom ersten. Der Regler im Bild wechselt genau diese Regel, nicht bloß die Darstellung.",
 "Prüfe den Aushang wie eine Liste zulässiger Abläufe. „Genau einmal rot“ erlaubt RB und BR, aber kein RR. Mit Zurücklegen liefern die beiden Pfade je 12/49, zusammen 24/49. „Mindestens einmal rot“ erlaubt zusätzlich RR; mit dessen 9/49 werden daraus 33/49. Du kannst auch beim ausgeschlossenen Rest anfangen: Nur BB mit 16/49 bleibt unpassend, also 1−16/49 = 33/49. Beide Wege müssen dieselbe Chance ergeben. Bei drei Zügen mit ausdrücklich verlangter Reihenfolge RBR zählt hingegen nur dieser eine Pfad. Ein anderes Schild mit „zweimal rot, einmal blau“ würde mehr Abläufe einschließen. Die genaue Sprache entscheidet also noch vor jeder Multiplikation über die Rechnung.",
 "Bei der Menüplanung verzweigt jede Vorspeise in vier Hauptspeisen und jede davon in zwei Desserts. Drei Vorspeisen ergeben damit 3·4·2 = 24 Möglichkeiten, sofern jede Kombination erlaubt ist. Diese Anzahl ist keine Wahrscheinlichkeit und sagt nichts über beliebte Menüs. Für eine erwartete Trefferzahl der Ziehaktion ist die Frage anders: Bei n Versuchen mit Trefferchance p ist der langfristige Mittelwert np. So ergeben 14 Versuche bei p = 3/7 die Erwartung 6. Eine einzelne Runde muss nicht sechs Treffer haben. Haltet im Plan deshalb Möglichkeiten, Chancen und erwartete Anzahlen getrennt fest; keine dieser Angaben ist ein Versprechen für den tatsächlichen Nachmittag."
 ],
 mistakes:'Nicht Farben statt Kugeln zählen: Rot und Blau haben nicht automatisch je 1/2. Nicht Zweigwahrscheinlichkeiten addieren, wenn ein gemeinsamer Pfad gemeint ist. Ohne Zurücklegen den richtigen Zähler und Nenner verändern. Im Antwortfeld wird hier der Anteil 0 bis 1 verlangt, nicht die Prozentzahl. Eine erwartete Häufigkeit kann auch nichtganzzahlig sein.',
 checks:[['Was ist das Gegenereignis zu mindestens einmal rot bei zwei Zügen?','Keinmal rot, also zweimal blau; nicht „genau einmal blau“.'],['Muss bei drei Zügen RBR mit drei multipliziert werden?','Nein, wenn genau diese Reihenfolge gefordert ist. Das ist nur ein Pfad.'],['Bedeutet erwartete Häufigkeit 6, dass genau 6 Treffer auftreten?','Nein. Es ist ein Mittelwert über viele vergleichbare Versuchsreihen.']],
},
{
 id:'daten',
 recall:'Eine Datenliste enthält Beobachtungen; gleiche Werte können mehrfach vorkommen und zählen dann mehrfach. Sortieren heißt numerisch von klein nach groß, auch mit negativen Zahlen. Ein Anteil ist Anzahl/Gesamtzahl und wird für Prozent mit 100 multipliziert. Eine Änderung ist Endwert minus Anfangswert; bei einer täglichen Rate teilt man durch die verstrichene Zeit, nicht durch die Anzahl der Messpunkte.',
 concepts:[['Mittelwert und Median','Das arithmetische Mittel verteilt die Summe gleichmäßig auf alle Beobachtungen. Der Median teilt die sortierte Liste in eine untere und eine obere Hälfte; bei gerader Anzahl werden die beiden mittleren Werte gemittelt.'],['Spannweite und Häufigkeiten','Die Spannweite ist Maximum minus Minimum. Absolute Häufigkeit zählt Beobachtungen, relative Häufigkeit beschreibt ihren Anteil. Ein gewichtetes Mittel berücksichtigt unterschiedliche Häufigkeiten.'],['Stichprobe, Zielgruppe, Trend','Eine Stichprobe ist die tatsächlich untersuchte Auswahl, die Zielgruppe die Gesamtheit, über die man sprechen möchte. Ein zeitlicher Trend beschreibt eine Veränderung, beweist aber keine Ursache.']],
 reasoning:[
 "Fragt für euren Bericht zuerst, was der Durchschnitt leisten soll. Das arithmetische Mittel beantwortet eine Verteilungsfrage: Welcher gleiche Wert würde bei derselben Zahl von Beobachtungen dieselbe Gesamtsumme ergeben? Dafür addierst du alle Werte und teilst durch ihre Anzahl. Ein einzelner sehr hoher Wert erhöht die Summe und zieht das Mittel mit nach oben. Der Median fragt dagegen nach der Mitte der sortierten Beobachtungen. Ein äußerer Wert kann wachsen, ohne dass diese Mitte ihre Position ändert. Das macht den Median bei einzelnen Ausreißern oft hilfreicher, aber nicht grundsätzlich besser. Benenne im Bericht die Frage, bevor du einen Kennwert auswählst; „der Durchschnitt“ allein ist zu ungenau.",
 "Bei den vier Zeitabweichungen 3, 4, 2, −2 ist die Summe 7, also das Mittel 7/4 = 1,75 Minuten. Für den Median brauchst du einen anderen Arbeitsschritt: sortieren zu −2, 2, 3, 4. Weil zwei Werte in der Mitte stehen, nimmst du deren Mittel, (2+3)/2 = 2,5 Minuten. Die Spannweite betrachtet nur die Ränder: 4−(−2) = 6 Minuten. Das Minus vor −2 ist wichtig, denn der Abstand führt von zwei Minuten vor bis vier Minuten nach der geplanten Zeit. Keiner dieser Kennwerte ist eine Anzahl von Aktionen. Auch gleiche Kennwerte würden nicht beweisen, dass zwei Datenlisten im Inneren gleich verteilt sind.",
 "Eine Häufigkeitstabelle spart Schreibarbeit, darf aber keine Beobachtungen verschwinden lassen. Dreimal der Wert 2 und viermal der Wert 5 steht für 2, 2, 2, 5, 5, 5, 5. Daher rechnest du (3·2+4·5)/(3+4), nicht (2+5)/2. Die Häufigkeiten gewichten jeden Wert so oft, wie er wirklich vorkommt. Für den Anteil einer Kategorie teilst du ebenfalls durch die Gesamtzahl der Beobachtungen. Schreibe diese Bezugsgruppe im Bericht aus. Ein Anteil unter sieben Rückmeldungen ist weder automatisch der Anteil aller Teilnehmenden noch die genaue Wahrscheinlichkeit einer kommenden Antwort. Die Rechnung kann richtig sein, während eine zu weit gefasste Aussage über die Gruppe falsch ist.",
 "Bei den Modellwerten 23 und 27 beginnt die verkürzte Balkenachse bei 20. Sichtbar bleiben dann Höhen von 3 und 7. Das Bild zeigt also das Verhältnis 7/3, obwohl die Daten im Verhältnis 27/23 stehen. Ein Nullbeginn stellt den passenden Größenvergleich wieder her; eine verkürzte Achse muss deutlich gekennzeichnet werden. Prüfe daneben die Datenauswahl: Wer nur eine Sport-AG befragt, hat andere Lernende nicht erfasst. Die Auslassungsquote beschreibt diese Lücke, nicht Richtung oder Stärke jeder möglichen Verzerrung. Auch beim Trend ist Zurückhaltung nötig. Von Tag 0 bis Tag 2 vergehen zwei Tage, nicht drei; eine mittlere tägliche Änderung beschreibt weder jeden einzelnen Tag noch die Ursache der Entwicklung."
 ],
 mistakes:'Vor dem Median wirklich sortieren. Bei Häufigkeiten durch die Gesamtzahl der Beobachtungen teilen, nicht durch die Zahl verschiedener Werte. Für Diagrammverhältnisse den Achsenbeginn berücksichtigen und sichtbares Verhältnis von Datenverhältnis trennen. Eine große Stichprobe heilt keine systematisch ausgelassene Gruppe. Ein gemeinsamer Trend ist kein Kausalnachweis.',
 checks:[['Was reagiert meist stärker auf einen einzelnen extrem hohen Wert: Mittel oder Median?','Das Mittel, weil der extreme Wert vollständig in die Summe eingeht. Der Median orientiert sich an der Mitte der sortierten Liste.'],['Zählt die Spannweite die Anzahl verschiedener Werte?','Nein. Sie ist größter minus kleinster Wert und hat dieselbe Einheit wie die Messwerte.'],['Warum ist eine Sport-AG allein keine gute Schulstichprobe zum Sportinteresse?','Die Auswahl hängt gerade mit dem untersuchten Interesse zusammen; andere Lernende werden systematisch nicht erfasst.']],
}
];

// Redaktioneller Zusammenhang und fachlicher Kern werden gemeinsam gerendert.
// Vier Fragen führen jeweils von einer Vorhersage zur begründeten Methode.
export const chapters = foundations.map(c => {
 const story=stories[c.id];
 if(!story || story.bridges.length!==c.reasoning.length)throw Error(`Unvollständiger Lernweg: ${c.id}`);
 return {...c,question:story.question,motivation:story.opening.join(' '),story,
  reasoning:c.reasoning.flatMap((text,i)=>[story.bridges[i][1],text]),
  reasoningSections:c.reasoning.map((text,i)=>({title:story.bridges[i][0],paragraphs:[story.bridges[i][1],text]})),
  summary:story.synthesis};
});
