// Eigenständige Lehrtexte; IDs stammen unverändert aus catalog.js.
export const chapters = [
{
 id:'zahlen', question:'Wie beschreibt man winzige Bauteile und große Datenmengen, ohne sich in Nullen zu verlieren?',
 motivation:'Ein Sensor kann nur wenige Millionstel Meter breit sein, eine Datei dagegen Millionen Zeichen enthalten. Brüche beschreiben Anteile, Potenzen wiederholte Multiplikation und Wurzeln die Suche nach einer passenden Seitenlänge. Diese Schreibweisen sind keine verschiedenen Zahlwelten: Sie erlauben, dieselbe Größe übersichtlich und vergleichbar auszudrücken. In diesem Kapitel lernst du, zwischen den Darstellungen zu wechseln und Ergebnisse schon vor dem Rechnen einzuschätzen.',
 recall:'Ein Bruch a/b bedeutet a geteilt durch b; b darf nicht null sein. Zähler und Nenner mit derselben von null verschiedenen Zahl zu multiplizieren ändert seinen Wert nicht: 1/2 = 2/4. Beim Multiplizieren zweier Brüche multipliziert man Zähler mit Zähler und Nenner mit Nenner. Ein negativer und ein positiver Faktor ergeben ein negatives Produkt. Klammern gehen vor Potenzen, Potenzen vor Punktrechnung und diese vor Strichrechnung.',
 concepts:[['Basis und Exponent','In 3⁴ ist 3 die Basis und 4 der Exponent: vier Faktoren 3 ergeben 81. Der Exponent sagt nicht, dass man 3 mit 4 multipliziert.'],['Kehrwert','Der Kehrwert von a/b ist b/a, sofern a und b nicht null sind. Ihr Produkt ist 1. Auch 3⁻² ist ein Kehrwert: 1/3².'],['Quadratwurzel und reelle Zahl','√N bezeichnet für N ≥ 0 die nichtnegative Zahl, deren Quadrat N ergibt. Manche Wurzeln sind keine Brüche, etwa √2. Rationale und irrationale Zahlen bilden zusammen die reellen Zahlen.']],
 reasoning:[
 'Warum darf man gleichnamige Brüche über die Zähler addieren? Ein Fünftel bleibt ein Fünftel, egal wie viele Stücke du zählst. Drei Fünftel und zwei Fünftel sind fünf Fünftel, nicht fünf Zehntel. Bei verschiedenen Nennern müsste man zuerst gleich große Stücke herstellen. Die Additionsaufgabe hier hat bereits gleiche Nenner; die Division verlangt dagegen eine andere Methode.',
 'Die Potenzgesetze lassen sich an Faktoren verstehen: 3² · 3³ enthält insgesamt fünf Faktoren 3. Bei 3⁵ : 3² kürzen sich zwei davon weg. Für 3² : 3⁵ bleibt 1/3³. Damit die Regel „Exponenten subtrahieren“ auch hier gilt, definiert man 3⁻³ = 1/3³. Ebenso ergibt 3³ : 3³ = 1 den Exponenten 0. Die Basis 0 ist bei Kehrwerten ausgeschlossen.',
 'Bei (3²)³ steht dreimal der Block 3²: insgesamt sechs Faktoren. Deshalb werden hier Exponenten multipliziert. Diese Gesetze betreffen Produkte, nicht Summen: 3² + 3³ kann nicht durch Addieren der Exponenten vereinfacht werden. Wissenschaftliche Schreibweise nutzt die Basis 10; eine normierte positive Zahl hat dabei einen Vorfaktor von mindestens 1 und kleiner als 10.',
 'Beim Einschachteln nutzt du, dass Quadrieren für nichtnegative Zahlen die Reihenfolge erhält. Aus 9 ≤ 11 < 16 folgt 3 ≤ √11 < 4. Ein Dezimalwert ist dafür unnötig. Die Aussage benennt ein Intervall und ist keine Behauptung, √11 sei genau 3.'
 ],
 mistakes:'Ein Minus im Exponenten ist kein negatives Ergebnis. 3⁻² = 1/9, nicht −9. Beim Teilen nur den zweiten Bruch umdrehen. Bei Potenzgesetzen zuerst prüfen: gleiche Basis und wirklich ein Produkt oder Quotient? Kontrolliere kleine Zahlen durch Rückmultiplikation und Zehnerpotenzen durch die Größenordnung.',
 checks:[['Warum ist 5⁻² positiv?','Es ist der Kehrwert 1/25 einer positiven Zahl; das Minus beschreibt die Kehrwertbildung.'],['Zwischen welchen ganzen Zahlen liegt √30?','Zwischen 5 und 6, denn 25 < 30 < 36. Die größte ganze Zahl darunter ist 5.'],['Ist (2³)² dasselbe wie 2³ · 2²?','Nein. Links stehen sechs Faktoren 2 (64), rechts fünf (32).']],
 summary:'Brüche brauchen passende Rechenregeln; Potenzgesetze zählen oder kürzen Faktoren. Negative Exponenten führen zu Kehrwerten, Zehnerpotenzen ordnen Größen und Quadratzahlen begrenzen Wurzeln. Entscheide zuerst anhand des Rechenzeichens, welche Regel passt.'
},
{
 id:'gleichungen', question:'Wie findest du einen unbekannten Preis, wenn nur eine Gesamtrechnung bekannt ist?',
 motivation:'Drei gleiche Tickets und vier Euro Buchungsgebühr ergeben einen Gesamtpreis. Die unbekannte Größe lässt sich durch x vertreten, statt Preise zu raten. Bei Flächen entsteht x²; bei zwei verschiedenen Ticketarten braucht man zwei Gleichungen. Das Kapitel verbindet diese Situationen: Terme beschreiben Rechenvorschriften, Gleichungen Bedingungen, und Lösungen sind genau die Werte, die diese Bedingungen erfüllen.',
 recall:'Eine Variable ist ein Platzhalter für eine Zahl. 3x bedeutet 3 · x. Eine Klammer wird mit dem Distributivgesetz ausmultipliziert: a(b+c) = ab+ac. Gleichartige Terme lassen sich zusammenfassen, etwa 2x+3x = 5x; x und x² sind dagegen nicht gleichartig. Für negative Zahlen gilt beispielsweise (−5)² = 25, aber −5² = −25. Lies Klammern deshalb sorgfältig.',
 concepts:[['Term, Gleichung, Lösung','Ein Term wie 3x+4 hat allein kein Wahrheitszeichen. Eine Gleichung setzt zwei Terme gleich. Eine Lösung macht nach dem Einsetzen beide Seiten gleich.'],['Äquivalenzumformung','Eine Umformung, die die Lösungsmenge erhält: dieselbe Zahl auf beiden Seiten addieren oder subtrahieren; mit derselben von null verschiedenen Zahl multiplizieren oder durch sie teilen.'],['Faktor und Nullprodukt','Faktoren sind die Teile einer Multiplikation. Ein Produkt reeller Zahlen ist genau dann null, wenn mindestens ein Faktor null ist. Für eine Summe gilt das nicht.']],
 reasoning:[
 'Eine Gleichung funktioniert wie eine ausgeglichene Waage. Entfernst du auf beiden Seiten denselben Betrag, bleibt das Gleichgewicht. Um 3x+4 = −2 zu lösen, entfernst du zuerst die Addition und dann die Multiplikation. Die Reihenfolge kehrt die Entstehung des Terms um. Durch x zu teilen wäre dagegen riskant: x könnte null sein und dann als Lösung verloren gehen.',
 'Die erste binomische Formel ist das Distributivgesetz zweimal angewendet: (x+d)(x+d) = x²+dx+dx+d² = x²+2dx+d². Die zwei gemischten Produkte erklären den häufig vergessenen Mittelterm. Bei (x−d)(x+d) entstehen +dx und −dx; sie heben sich auf. Übrig bleibt x²−d². Die Flächenzeichnung unten macht für positive Längen die erste Formel sichtbar; die algebraische Rechnung gilt auch für negative x.',
 'Eine quadratische Gleichung muss nicht genau zwei verschiedene Lösungen haben. x² = 25 liefert −5 und 5, x² = 0 nur 0, x² = −1 keine reelle Lösung. Aus einer bereits faktorisierten Form liest du Lösungen über das Nullprodukt ab. Um x²+sx+p zu faktorisieren, suche u und v mit u+v = s und uv = p. Dann ergibt Ausmultiplizieren (x+u)(x+v) genau den ursprünglichen Term. In diesen Übungen sind passende ganzzahlige Faktoren vorhanden; das ist keine Universalmethode für jede quadratische Gleichung.',
 'Ein Gleichungssystem verlangt, dass beide Bedingungen gleichzeitig gelten. Addiert man x+y = 2 und x−y = −6, verschwindet y, weil y+(−y) = 0. Danach bestimmst du y durch Einsetzen. Nur x zu kennen erfüllt zwar das Antwortfeld dieser Übung, aber erst die Probe in beiden Gleichungen sichert das Zahlenpaar.'
 ],
 mistakes:'Nicht nur eine Seite verändern. Nicht (x+5)² mit x²+25 verwechseln. Nicht aus einem Produkt x−3 = 0 UND x+4 = 0 verlangen: Es genügt ODER. Bei mehrfach auftretender gleicher Wurzel die Lösung nur einmal nennen. Alle gefundenen Werte in die ursprüngliche Gleichung einsetzen.',
 checks:[['Darfst du 2x = 0 durch x teilen?','Nicht ohne Fallunterscheidung: x = 0 ist gerade die Lösung und Division durch null ist nicht erlaubt. Teile stattdessen durch 2.'],['Welche Zahl steht vor x in (x+7)²?','14, weil die beiden gemischten Produkte je 7x ergeben.'],['Warum genügt eine Probe nur in der ersten LGS-Gleichung nicht?','Ein Zahlenpaar kann eine Bedingung erfüllen und die andere verletzen; ein System verlangt beide.']],
 summary:'Löse Gleichungen durch umkehrbare Schritte und kontrolliere durch Einsetzen. Binomische Formeln entstehen durch Ausmultiplizieren, Faktorisieren macht das Nullprodukt nutzbar. Beim LGS beseitigst du eine Variable und prüfst anschließend beide Bedingungen.'
},
{
 id:'linear', question:'Welcher Leihradtarif ist günstiger – und ab wann wechselt die Antwort?',
 motivation:'Ein Tarif hat eine niedrige Startgebühr, ein anderer einen niedrigen Stundenpreis. Ein einzelner Preisvergleich genügt nicht: Die Nutzungsdauer entscheidet. Lineare Funktionen beschreiben einen konstanten Zuwachs pro Einheit. Du lernst, von einer Vorschrift zu Werten, von Messpunkten zu einer Vorschrift und von zwei Tarifen zu ihrem Schnittpunkt zu gelangen.',
 recall:'Ein Punkt P(x|y) nennt zuerst die waagerechte, dann die senkrechte Koordinate. Eine Differenz ist Endwert minus Anfangswert und kann negativ sein. Brüche drücken auch Verhältnisse aus. Eine Gleichung ax+b = c löst du durch Subtrahieren von b und Teilen durch a, sofern a ≠ 0. Beim Einsetzen eines negativen x helfen Klammern: 2 · (−2)+4 = 0.',
 concepts:[['Funktion und Funktionswert','Eine Funktion ordnet jedem zulässigen x genau einen Wert y = f(x) zu. Der Graph besteht aus den Punkten (x|f(x)).'],['Steigung m','In f(x) = mx+b gibt m die Änderung von y pro zusätzlicher Einheit x an. Positives m bedeutet Anstieg, negatives m Abnahme. Die Einheit kann beispielsweise Euro je Stunde sein.'],['Achsenabschnitt b und Nullstelle','b = f(0) ist der Schnitt mit der y-Achse. Eine Nullstelle ist ein x-Wert mit f(x) = 0 und liegt auf der x-Achse. Das sind unterschiedliche Angaben.']],
 reasoning:[
 'Aus f(x+Δx)−f(x) = m(x+Δx)+b−(mx+b) bleibt mΔx. Der Achsenabschnitt hebt sich auf: Er verschiebt alle Werte gleich stark, verändert aber nicht die Rate. Deshalb sind die Steigungsdreiecke entlang derselben Geraden ähnlich und liefern immer Δy/Δx = m. Bei zwei Punkten müssen beide Differenzen in derselben Richtung gebildet werden; senkrechte Geraden mit Δx = 0 sind nicht als y = mx+b darstellbar.',
 'Mit bekanntem m und einem Punkt folgt aus y = mx+b unmittelbar b = y−mx. Damit nutzt du nicht das Aussehen des Graphen als Schätzung, sondern die exakte Punktbedingung. Anschließend berechnest du weitere Werte durch Einsetzen. Umgekehrt wird aus einem vorgegebenen Funktionswert eine Gleichung für x. An einer Nullstelle ist dieser vorgegebene Wert besonders einfach: null.',
 'Am Schnittpunkt zweier Funktionsgraphen stimmen x UND y überein. Deshalb setzt man ihre Funktionsterme gleich, löst nach x und setzt dieses x in einen Term ein, um y zu erhalten. Bei gleichen Steigungen können zwei verschiedene Geraden parallel sein und keinen Schnittpunkt haben; identische Geraden haben unendlich viele gemeinsame Punkte. Der Aufgabengenerator wählt unterschiedliche Steigungen.',
 'Ein Kostenmodell b+mx setzt voraus, dass die Grundgebühr genau einmal anfällt und jede Einheit denselben Preis hat. In der Realität können Tageshöchstpreise, Rabatte oder angefangene Stunden das Modell einschränken. Negative Nutzungsdauer ist zwar algebraisch einsetzbar, aber im Sachzusammenhang sinnlos. Notiere daher neben der Rechnung die Bedeutung der Zahlen und den sinnvollen Eingabebereich.'
 ],
 mistakes:'Steigung ist nicht y/x, außer die Gerade geht durch den Ursprung. Vertausche nicht Δx und Δy. Ein negativer Änderungswert bedeutet Abnahme, nicht eine negative Dauer. Ein Schnittpunkt ist ein Punkt; wenn das Antwortfeld nur x verlangt, darf dort trotzdem nicht das Zahlenpaar stehen.',
 checks:[['Ändert eine höhere Grundgebühr die Steigung?','Nein. Sie ändert b, während der Preis je Einheit m gleich bleibt.'],['Eine Gerade fällt bei Δx = 3 um 6. Welche Steigung hat sie?','m = −6/3 = −2. Das Minus kennzeichnet die Abnahme.'],['Was prüfst du nach einer Schnittpunktrechnung?','Dass beide Funktionsterme beim gefundenen x denselben y-Wert liefern.']],
 summary:'Lineare Funktionen haben konstante Änderungsraten. Δy/Δx liefert m, ein Punkt danach b. Einsetzen gibt Ausgaben, Gleichungen geben Eingaben; Gleichsetzen findet gemeinsame Punkte. Prüfe bei Modellen zusätzlich Einheiten und Gültigkeitsbereich.'
},
{
 id:'quadratisch', question:'Wo liegt der tiefste Punkt einer parabelförmigen Rinne?',
 motivation:'Bei einer Rinne interessieren der tiefste Punkt und die Höhe in einem bestimmten Abstand von der Mitte. Bei einem nach unten geöffneten Bogen dagegen der höchste Punkt und die Stellen auf Bodenniveau. Quadratische Funktionen verbinden diese Fragen. Die Scheitelform zeigt Lage, Symmetrie und Öffnung, ohne dass du eine lange Wertetabelle ausrechnen musst.',
 recall:'Ein Quadrat ist für reelle Zahlen immer nichtnegativ: (−3)² = 3² = 9. Die Quadratwurzel √9 ist die nichtnegative Zahl 3; die Gleichung x² = 9 hat dennoch zwei Lösungen. Eine Funktion ordnet x einen y-Wert zu. Die Nullstelle ist ein x-Wert mit y = 0. Klammer, Quadrat, Multiplikation und Addition werden in dieser Reihenfolge berechnet.',
 concepts:[['Scheitelform','f(x) = a(x−h)²+k mit a ≠ 0. Der Scheitel liegt bei S(h|k), weil dort x−h = 0 ist.'],['Öffnung und Streckung','a > 0 öffnet nach oben, a < 0 nach unten. Größeres |a| bedeutet bei gleichem Abstand vom Scheitel größere Höhenunterschiede und damit eine schmalere Parabel.'],['Symmetrieachse und Extremwert','Die Gerade x = h ist die Symmetrieachse. Bei a > 0 ist k ein Minimum, bei a < 0 ein Maximum, sofern alle reellen x zugelassen sind.']],
 reasoning:[
 'Die Normalparabel y = x² hat ihr Minimum bei (0|0). Ersetzt man x durch x−h, wird das Quadrat bei x = h null: Die Parabel wandert bei positivem h nach rechts. Das wirkt zunächst gegen die Schreibweise in der Klammer. Außerhalb der Klammer addiertes k verschiebt dagegen jeden Funktionswert unmittelbar um k nach oben oder unten.',
 'Setze x = h+d und x = h−d ein. Die Klammer ergibt d beziehungsweise −d, und beide Quadrate sind d². Deshalb liegen gleich hohe Punkte gleich weit links und rechts vom Scheitel. Ihre x-Koordinaten addieren sich zu 2h. Bei x = h selbst existiert kein anderer Spiegelpunkt; die Übungen wählen deshalb einen von null verschiedenen Abstand.',
 'Für Nullstellen setzt du a(x−h)²+k = 0, subtrahierst k und teilst durch a. Jetzt entscheidet die rechte Seite r = −k/a: Bei r > 0 sind x = h−√r und x = h+√r die beiden Lösungen, bei r = 0 nur h, bei r < 0 keine reelle Lösung. Das zeigt auch geometrisch, ob die Parabel die x-Achse zweimal schneidet, berührt oder gar nicht trifft.',
 'Ist der Scheitel bekannt und zusätzlich ein anderer Punkt P, bleibt nur a unbekannt. Aus yP−k = a(xP−h)² folgt a = (yP−k)/(xP−h)². Der Zusatzpunkt darf nicht der Scheitel sein, sonst würdest du durch null teilen und jede Öffnungsweite wäre möglich. Die Verfahren hier arbeiten mit gegebener Scheitelform, nicht mit einer beliebigen allgemeinen quadratischen Gleichung.'
 ],
 mistakes:'In (x+5)² steht h = −5, nicht 5. Das Minimum ist ein y-Wert, der Scheitel ein Punkt und eine Nullstelle ein x-Wert. Nach dem Wurzelziehen beide Vorzeichen berücksichtigen. Runden erst am Schluss. Bei Sachmodellen kontrollieren, ob der Scheitel überhaupt im erlaubten Bereich liegt.',
 checks:[['Wo liegt der Scheitel von −2(x+3)²+7?','Bei S(−3|7). Wegen a = −2 ist 7 der größte, nicht der kleinste Funktionswert.'],['Wie viele reelle Lösungen hat (x−4)² = −2?','Keine: Kein reelles Quadrat ist negativ.'],['Welche x-Koordinate ist zu x = 8 an x = 3 gespiegelt?','−2. Beide liegen im Abstand 5 von der Symmetrieachse; 8+(−2) = 2 · 3.']],
 summary:'Lies h und k über die verschwindende Klammer ab. Quadrate erklären Minimum, Maximum und Symmetrie. Nullstellen entstehen durch Isolieren des Quadrats und eine Vorzeichenentscheidung. Ein weiterer Punkt bestimmt die Streckung.'
},
{
 id:'trigonometrie', question:'Wie hoch ist ein Baum, dessen Spitze du unter einem gemessenen Winkel siehst?',
 motivation:'Mit Abstand und Blickwinkel kannst du eine unzugängliche Höhe berechnen. Dafür brauchst du ein rechtwinkliges Hilfsdreieck; die Augenhöhe kommt im realen Modell noch dazu. Andere Vermessungen liefern zwei Seiten und den eingeschlossenen Winkel, aber keinen rechten Winkel. Hier lernst du zu entscheiden, wann Pythagoras, Sinus, Kosinus, Tangens oder die allgemeinen Dreieckssätze passend sind.',
 recall:'Die Winkelsumme im Dreieck ist 180°. Ein rechter Winkel misst 90°. Die Fläche ist Grundseite mal zugehörige senkrechte Höhe geteilt durch 2. Seitenlängen sind positiv. Quadrate und Quadratwurzeln machen einander für nichtnegative Zahlen rückgängig. Am Taschenrechner bedeutet DEG Gradmaß; RAD wäre für diese Übungen falsch. Die Umkehrfunktion arctan oder tan⁻¹ ist nicht der Kehrwert 1/tan.',
 concepts:[['Hypotenuse und Katheten','Im rechtwinkligen Dreieck liegt die Hypotenuse gegenüber 90° und ist die längste Seite. Die beiden Seiten am rechten Winkel heißen Katheten.'],['Gegen- und Ankathete','Diese Namen hängen vom gewählten spitzen Winkel α ab. Die Gegenkathete liegt gegenüber α; die Ankathete liegt an α und ist nicht die Hypotenuse.'],['Trigonometrische Verhältnisse','sin α = g/c, cos α = a/c, tan α = g/a. In allgemeinen Dreiecken steht die Seite a gegenüber α, b gegenüber β und c gegenüber γ.']],
 reasoning:[
 'Vergrößert man ein rechtwinkliges Dreieck bei gleichem Winkel, wachsen alle Seiten im selben Verhältnis. Die Quotienten g/c, a/c und g/a bleiben deshalb gleich. Genau diese winkelabhängigen Verhältnisse heißen Sinus, Kosinus und Tangens. Sie sind keine Seitenlängen. Wähle das Verhältnis, in dem die bekannte und die gesuchte Seite vorkommen, und forme erst dann um.',
 'Pythagoras a²+b² = c² verbindet im rechtwinkligen Dreieck die Flächen der Seitenquadrate. Zur Hypotenuse addierst du die Kathetenquadrate und ziehst die positive Wurzel. Die Summe der Seiten selbst wäre ein Weg über die Ecke und länger als die direkte Verbindung. Bei bekanntem Verhältnis g/a suchst du mit arctan den Winkel, dessen Tangens dieser Quotient ist.',
 'Auch ein schiefes Dreieck lässt sich durch eine Höhe in rechtwinklige Dreiecke zerlegen. Die gemeinsame Höhe liefert b sin α = a sin β und damit a/sin α = b/sin β. Deshalb brauchst du beim Sinussatz ein bekanntes Gegenüberpaar. Hier sind zwei Winkel und eine gegenüberliegende Seite gegeben; die Winkel ergeben zusammen weniger als 180°. Andere Angaben können mehrdeutige Fälle erzeugen, die dieser Trainer nicht behandelt.',
 'Beim Kosinussatz projizierst du die Seite b auf a: Die waagerechte Komponente ist b cos γ, die senkrechte b sin γ. Pythagoras liefert c² = (a−b cos γ)²+(b sin γ)². Beim rechtwinkligen Dreieck mit Hypotenuse 1 folgt aus Pythagoras sin² γ+cos² γ = 1; die Einheitskreisdefinition erhält diese Identität für alle Winkel. Nach Ausmultiplizieren und Zusammenfassen bleibt a²+b²−2ab cos γ. Für γ = 90° verschwindet der letzte Term: Pythagoras ist der Spezialfall. Dieselbe senkrechte Komponente liefert die Fläche A = a·b·sin γ/2. Der Winkel muss zwischen den beiden benutzten Seiten liegen.'
 ],
 mistakes:'Pythagoras und die Kathetenquotienten gelten nur im rechtwinkligen Dreieck. Sinus- und Kosinussatz dagegen auch im allgemeinen. Markiere vor der Rechnung Winkel und gegenüberliegende Seiten. Eine Kathete kann nicht länger als die Hypotenuse sein; ein Dreieck muss außerdem die Dreiecksungleichung erfüllen. Runde erst das Endergebnis auf zwei Nachkommastellen.',
 checks:[['Du kennst Ankathete und Winkel, suchst Gegenkathete. Welche Funktion?','Tangens, denn tan α = Gegenkathete/Ankathete.'],['Warum wird der Kosinussatz bei 90° zu Pythagoras?','cos 90° = 0; der Korrekturterm −2ab cos γ fällt weg.'],['Warum genügt für eine Fläche nicht die schräge Seite als Höhe?','Die Flächenformel benötigt eine senkrechte Höhe; aus der schrägen Seite b wird h = b sin γ.']],
 summary:'Skizze, rechtwinklig oder allgemein, bekannte Größen markieren, passende Beziehung wählen, umformen, rechnen, prüfen. Die Seitenquotienten folgen aus Ähnlichkeit; Höhen verbinden sie mit den allgemeinen Dreieckssätzen und der Fläche.'
},
{
 id:'koerper', question:'Wie viel Material braucht ein Behälter – und wie viel passt hinein?',
 motivation:'Eine kegelförmige Verpackung braucht Karton für ihre Oberfläche, aber ihr Fassungsvermögen ist ein Volumen. Bei einer Kuppel auf einem Zylinder setzt sich der Innenraum aus zwei Teilen zusammen. Dieselben Längen treten in verschiedenen Formeln auf; entscheidend ist, ob eine Fläche oder ein Rauminhalt gefragt ist. Dieses Kapitel ordnet Formeln nach Bedeutung, statt sie als austauschbare Buchstabenfolgen zu behandeln.',
 recall:'Ein Rechteck hat Fläche Länge mal Breite, ein Kreis G = πr². Der Radius r ist die halbe Länge des Durchmessers. Ein Prisma oder Zylinder mit konstanter Grundfläche hat V = G·h. Pythagoras verbindet rechtwinklige Seiten durch a²+b² = c². Zentimeter, Quadratzentimeter und Kubikzentimeter messen unterschiedliche Dinge. Nutze die π-Taste und runde nicht schon π auf 3,14.',
 concepts:[['Volumen und Oberfläche','V misst den gefüllten Raum in cm³. O misst die gesamte äußere Fläche in cm². Eine Mantelfläche M schließt die Grundfläche gerade nicht ein.'],['Senkrechte Höhe und Mantellinie','h steht senkrecht auf der Grundfläche. Beim geraden Kegel läuft die Mantellinie s schräg von der Spitze zum Kreisrand; s² = r²+h².'],['Maßstab und Einheiten','Wächst jede Länge mit Faktor λ, wachsen Flächen mit λ² und Volumina mit λ³. Nano bedeutet 10⁻⁹ einer Grundeinheit, nicht eine neue geometrische Form.']],
 reasoning:[
 'Ein Kegel und eine Pyramide werden zur Spitze hin schmaler. Ihr Volumen ist ein Drittel des Prismas beziehungsweise Zylinders mit gleicher Grundfläche und senkrechter Höhe: V = G·h/3. Der Faktor 1/3 ist ein geometrischer Satz, der sich etwa durch Zerlegungen und Volumenvergleiche begründen lässt; eine einzelne Querschnittsskizze beweist ihn noch nicht. Anders als beim Zylinder sind die Querschnittsflächen nicht konstant.',
 'Rollst du einen Kegelmantel auseinander, erhältst du einen Kreissektor mit Radius s. Seine Bogenlänge ist der Umfang der Grundfläche, also 2πr. Ein voller Kreis mit Radius s hätte Umfang 2πs und Fläche πs². Der benötigte Anteil ist r/s; daraus folgt M = (r/s)·πs² = πrs. Für die geschlossene Oberfläche kommt der Grundkreis πr² hinzu. Wenn nur r und h gegeben sind, berechne zuvor s mit Pythagoras im Achsenschnitt.',
 'Für die Kugel gelten O = 4πr² und V = 4πr³/3. Die Oberfläche entspricht also flächenmäßig vier gleich großen Radiuskreisen, nicht vier flachen Stücken, in die sich die Kugel exakt ausrollen ließe. Ein anschaulicher Volumenvergleich verwendet eine Halbkugel und einen Zylinder minus Kegel: In jeder gleichen Höhe stimmen ihre Querschnittsflächen überein. Das Cavalieri-Prinzip begründet dann V der Halbkugel = πr³−πr³/3 = 2πr³/3. Die vollständige Kugel hat das Doppelte.',
 'Bei zusammengesetzten Körpern addierst du nicht überlappende Teilvolumina. Für äußere Oberflächen dürfte man dagegen gemeinsame Kontaktflächen nicht mitzählen. Die Übung mit Zylinder und Halbkugel fragt ausdrücklich das Volumen. Umrechnungen verlangen dieselbe Sorgfalt: 1 nm = 10⁻⁹ m; Flächen- oder Volumeneinheiten müssten einen Umrechnungsfaktor zusätzlich quadrieren beziehungsweise kubieren. Die Nano-Aufgabe hier betrifft nur eine Länge.'
 ],
 mistakes:'Nicht Radius und Durchmesser vertauschen: Ein verdoppelter Radius vervierfacht die Fläche und verachtfacht das Volumen. Beim Kegel h nicht für s einsetzen. Mantel und gesamte Oberfläche unterscheiden. Jede Formel mit Einheiten prüfen: r²h liefert Länge³, rs liefert Länge². Kleine Längen in Metern dürfen keinesfalls auf null „gerundet“ werden.',
 checks:[['Wie verändert sich ein Kugelvolumen bei doppeltem Radius?','Es wird achtmal so groß, weil (2r)³ = 8r³.'],['Warum ist die Kegelmantellinie länger als die Höhe?','Sie ist die Hypotenuse des Schnittdreiecks: s = √(r²+h²) > h für r > 0.'],['Darf man bei zwei verbundenen Körpern alle Oberflächen einfach addieren?','Nein. Gemeinsame Innenflächen gehören nicht zur äußeren Oberfläche. Teilvolumina ohne Überlappung darf man addieren.']],
 summary:'Frage zuerst: Länge, Fläche oder Volumen? Bestimme die geometrische Bedeutung jeder Größe. Kegel/Pyramide benötigen G·h/3, Kugeln Radiusformeln, der Kegelmantel die schräge Mantellinie. Addiere nur passende Teilgrößen und kontrolliere Einheiten.'
},
{
 id:'wachstum', question:'Warum ist jedes Jahr zehn Prozent mehr nicht dasselbe wie jedes Jahr zehn Stück mehr?',
 motivation:'Zinseszins und wiederholte Halbierung verändern einen Bestand relativ zu seiner aktuellen Größe. Eine Schwingung verhält sich anders: Sie wiederholt ihre Werte, etwa bei einem idealisierten Riesenrad ohne Höhenverschiebung. Beide Modellfamilien gehören hier zusammen zum Thema, aber nicht zur selben Formel. Du lernst, wiederholtes Multiplizieren von periodischer Bewegung zu unterscheiden und die Parameter beider Modelle zu deuten.',
 recall:'Prozent bedeutet Hundertstel: 12 % = 0,12. Nach einer Zunahme bleibt der alte Bestand erhalten und der Zuwachs kommt hinzu. Eine Potenz qⁿ bedeutet n gleiche Faktoren q. Division macht Multiplikation rückgängig. Im Gradmaß entspricht eine volle Umdrehung 360°. Der Sinus liegt zwischen −1 und 1 und wiederholt sich nach einer vollen Umdrehung.',
 concepts:[['Anfangsbestand N₀ und Faktor q','Im diskreten Modell N(n) = N₀·qⁿ ist n eine ganze nichtnegative Schrittzahl. q ist das Verhältnis zweier aufeinanderfolgender Bestände, nicht die absolute Differenz.'],['Zunahme, Zerfall, Halbwertszeit','q > 1 bedeutet Zunahme; 0 < q < 1 Abnahme. Bei jeder Halbwertszeit bleibt die Hälfte. q = 1 beschreibt einen konstanten Bestand.'],['Amplitude und Periode','Bei y = a sin(bx) ist |a| der maximale Abstand von der Mittellinie 0. Für b ≠ 0 beträgt die kleinste positive Periode im Gradmaß T = 360°/|b|.']],
 reasoning:[
 'Bei p Prozent Wachstum wird aus N der Wert N+(p/100)N = N(1+p/100). Deshalb ist q = 1+p/100. Nach dem nächsten Schritt wird auch der bereits hinzugekommene Anteil mitverändert: N₂ = N₀q·q. Durch Wiederholung entsteht Nₙ = N₀qⁿ. Beim Zerfall wird der verlorene Anteil subtrahiert, sodass q = 1−p/100. Das Modell setzt einen konstanten relativen Änderungsanteil pro gleich langem Schritt voraus.',
 'Verdopplung und Halbierung sind besonders übersichtliche Faktoren: 2 und 1/2. Eine Halbierung nimmt immer die Hälfte des noch vorhandenen Bestands weg, nicht erneut die Hälfte des Anfangswerts. Das Ergebnis nähert sich null, erreicht es nach endlich vielen Schritten bei positivem Anfangsbestand aber nicht. Ein Anfangsbestand wird rückwärts durch N₀ = N(n)/qⁿ rekonstruiert. Die Suche nach einer unbekannten allgemeinen Schrittzahl mit Logarithmen gehört nicht zu diesen Aufgaben.',
 'Die Sinusfunktion beschreibt die senkrechte Koordinate eines Punktes auf dem Einheitskreis in Abhängigkeit vom Drehwinkel. Nach 90° ist sie 1, nach 180° null, nach 270° −1, nach 360° wieder null. Der Vorfaktor a skaliert diese Höhe; ein negatives a spiegelt an der x-Achse. Die Amplitude bleibt positiv. Sie ist die halbe Spitze-zu-Spitze-Höhe, nicht die ganze.',
 'Der Faktor b verändert den inneren Winkel. Wenn x um T zunimmt, wächst bx um bT. Für eine volle Wiederholung muss der Betrag dieser Änderung 360° sein; deshalb T = 360°/|b|. Der äußere Faktor a hat darauf keinen Einfluss, sofern a nicht null ist. Die Übungen verwenden von null verschiedene Faktoren. Beim Funktionswert zuerst bx bilden, dann im Gradmaß den Sinus nehmen und zuletzt mit a multiplizieren. Ein Wachstumsgraf besteht hier aus diskreten Schrittwerten, eine Sinuskurve dagegen aus kontinuierlichen Winkelwerten.'
 ],
 mistakes:'10 % Wachstum bedeutet q = 1,10, nicht q = 0,10 oder 10. Verwechsle relative mit absoluter Änderung nicht. Bei Sinus ist das Minus vor a keine negative Amplitude; b ist nicht die Periode. Nutze DEG, auch wenn bx größer als 90° ist. Modelle sind Annahmen, keine Garantie realer unbegrenzter Zunahme.',
 checks:[['Wie viel bleibt nach zwei Halbierungen?','Ein Viertel des Anfangsbestands: (1/2)² = 1/4.'],['Welche Periode hat 4 sin(3x) im Gradmaß?','120°, weil sich der innere Winkel dann um 360° ändert.'],['Ist das Wachstum bei konstantem q auch jedes Mal absolut gleich groß?','Nein, außer in Sonderfällen wie q = 1. Der Zuwachs hängt vom aktuellen Bestand ab.']],
 summary:'Diskretes Wachstum multipliziert pro Schritt mit q; Prozentangaben liefern 1±p/100. Rückwärts teilst du durch qⁿ. Sinusmodelle wiederholen sich: |a| steuert die Höhe und 360°/|b| die Periode. Unterscheide Schrittzahl und Winkel.'
},
{
 id:'zufall', question:'Ist zweimal Ziehen dieselbe Chance wie einmal – und was ändert Zurücklegen?',
 motivation:'Ein Los kann günstig sein, zwei Ziehungen können aber sehr verschiedene Ereignisse meinen: zweimal Gewinn, genau ein Gewinn oder mindestens ein Gewinn. Die Wörter legen fest, welche Ergebnisse zählen. Ein Baumdiagramm hält die Reihenfolgen auseinander. Damit kannst du Wahrscheinlichkeiten berechnen, ohne „genau“ und „mindestens“ zu verwechseln oder beim zweiten Zug eine bereits entfernte Kugel mitzuzählen.',
 recall:'Ein Anteil günstige/alle liegt zwischen 0 und 1; 1/4 entspricht 25 %. Brüche werden durch Zähler mal Zähler und Nenner mal Nenner multipliziert. Getrennte Anteile desselben Ganzen dürfen addiert werden. Alle möglichen Ergebnisse zusammen haben Wahrscheinlichkeit 1. Ein Ereignis kann aus mehreren Ergebnissen bestehen: „genau eine rote Kugel“ enthält rot–blau und blau–rot.',
 concepts:[['Laplace-Modell','Günstige Ergebnisse geteilt durch alle Ergebnisse gilt, wenn die einzelnen Ergebnisse gleich wahrscheinlich sind. Bei gleichartigen, gut gemischten Kugeln sind die Kugeln die gleich wahrscheinlichen Ergebnisse, nicht automatisch die Farben.'],['Pfad- und Summenregel','Ein vollständiger Weg durch einen Baum hat die Wahrscheinlichkeit als Produkt seiner Zweigwahrscheinlichkeiten. Für mehrere einander ausschließende passende Pfade werden diese Produkte addiert.'],['Gegenereignis und Erwartung','Das Gegenereignis enthält genau alle nicht passenden Ergebnisse. P(E) = 1−P(nicht E). Die erwartete Häufigkeit nP(E) ist ein langfristiger Mittelwert, keine zugesagte Trefferzahl.']],
 reasoning:[
 'Warum multipliziert man entlang eines Pfades? Wenn etwa 3/7 der ersten Ergebnisse rot sind und innerhalb dieser Gruppe nochmals 3/7 rot gezogen wird, bleibt der Anteil (3/7)·(3/7). Der zweite Bruch beschreibt die Chance nach dem bereits gewählten ersten Zweig. Mit Zurücklegen und erneutem Mischen ist die Urne unverändert; ohne Zurücklegen hängt die zweite Chance von der ersten Farbe ab.',
 'Ohne Zurücklegen fehlen nach einer roten Kugel eine rote und eine Kugel insgesamt: Aus 3 roten und 4 blauen werden 2 rote und 4 blaue. Nach einer blauen wären es dagegen 3 rote und 3 blaue. Ein Baum kann deshalb auf der zweiten Stufe verschiedene Brüche tragen. Mit Zurücklegen ist die wiederholte Ziehung im Modell unabhängig; ohne Zurücklegen nicht.',
 '„Genau einmal rot“ sind die getrennten Pfade RB und BR. Ihr gleiches Produkt darf im Modell mit Zurücklegen doppelt genommen werden. „Mindestens einmal rot“ enthält zusätzlich RR. Häufig ist der einzige unpassende Pfad BB einfacher: 1−P(BB). Bei drei fest vorgegebenen Farben wie RBR zählt nur diese Reihenfolge, nicht jede Anordnung derselben Farben. Erst die Ereignisbeschreibung entscheidet, ob weitere Pfade hinzukommen.',
 'Die Produktregel fürs Zählen ist verwandt, aber keine Wahrscheinlichkeit: Bei 3 Vorspeisen, 4 Hauptspeisen und 2 Desserts verzweigt jede Wahl erneut, sodass 3·4·2 Menüs entstehen. Voraussetzung ist, dass alle Kombinationen erlaubt sind. Bei n wiederholten Versuchen mit Trefferchance p ist die erwartete Anzahl np. Einzelne Versuchsreihen können stark abweichen; mehr Versuche machen die vorhergesagte Anzahl nicht zur sicheren Aussage.'
 ],
 mistakes:'Nicht Farben statt Kugeln zählen: Rot und Blau haben nicht automatisch je 1/2. Nicht Zweigwahrscheinlichkeiten addieren, wenn ein gemeinsamer Pfad gemeint ist. Ohne Zurücklegen den richtigen Zähler und Nenner verändern. Im Antwortfeld wird hier der Anteil 0 bis 1 verlangt, nicht die Prozentzahl. Eine erwartete Häufigkeit kann auch nichtganzzahlig sein.',
 checks:[['Was ist das Gegenereignis zu mindestens einmal rot bei zwei Zügen?','Keinmal rot, also zweimal blau; nicht „genau einmal blau“.'],['Muss bei drei Zügen RBR mit drei multipliziert werden?','Nein, wenn genau diese Reihenfolge gefordert ist. Das ist nur ein Pfad.'],['Bedeutet erwartete Häufigkeit 6, dass genau 6 Treffer auftreten?','Nein. Es ist ein Mittelwert über viele vergleichbare Versuchsreihen.']],
 summary:'Übersetze zuerst die Wörter in passende Pfade. Entlang eines Pfades multiplizieren, disjunkte passende Pfade addieren. Ohne Zurücklegen ändern sich Anzahlen; Gegenereignisse können Rechenarbeit sparen. Chancen, Möglichkeiten und erwartete Häufigkeiten sind verschiedene Größen.'
},
{
 id:'daten', question:'Kann dieselbe Schulumfrage gleichzeitig richtig gerechnet und irreführend dargestellt sein?',
 motivation:'Zwei Diagramme können dieselben Zahlen zeigen und sehr verschieden wirken. Ein Durchschnitt kann einen typischen Wert beschreiben oder Ausreißer verdecken; eine Umfrage kann korrekt ausgezählt sein und trotzdem die Zielgruppe verfehlen. Dieses Kapitel verbindet Rechnen mit kritischem Lesen: Du bestimmst Kennwerte und prüfst, was sie aussagen – und was gerade nicht.',
 recall:'Eine Datenliste enthält Beobachtungen; gleiche Werte können mehrfach vorkommen und zählen dann mehrfach. Sortieren heißt numerisch von klein nach groß, auch mit negativen Zahlen. Ein Anteil ist Anzahl/Gesamtzahl und wird für Prozent mit 100 multipliziert. Eine Änderung ist Endwert minus Anfangswert; bei einer täglichen Rate teilt man durch die verstrichene Zeit, nicht durch die Anzahl der Messpunkte.',
 concepts:[['Mittelwert und Median','Das arithmetische Mittel verteilt die Summe gleichmäßig auf alle Beobachtungen. Der Median teilt die sortierte Liste in eine untere und eine obere Hälfte; bei gerader Anzahl werden die beiden mittleren Werte gemittelt.'],['Spannweite und Häufigkeiten','Die Spannweite ist Maximum minus Minimum. Absolute Häufigkeit zählt Beobachtungen, relative Häufigkeit beschreibt ihren Anteil. Ein gewichtetes Mittel berücksichtigt unterschiedliche Häufigkeiten.'],['Stichprobe, Zielgruppe, Trend','Eine Stichprobe ist die tatsächlich untersuchte Auswahl, die Zielgruppe die Gesamtheit, über die man sprechen möchte. Ein zeitlicher Trend beschreibt eine Veränderung, beweist aber keine Ursache.']],
 reasoning:[
 'Das arithmetische Mittel entsteht aus der Frage: Welchen gleichen Wert müssten alle Beobachtungen haben, damit die Gesamtsumme unverändert bleibt? Deshalb teilt man durch die Anzahl. Ein einzelner sehr großer Wert erhöht die Summe und damit das Mittel deutlich. Der Median hängt vor allem von der Reihenfolge ab; weit außen liegende Werte können wachsen, ohne dass sich die Mitte ändert. Kein Kennwert ist immer „der richtige“: Entscheidend ist die Frage.',
 'Bei vier sortierten Zahlen stehen zwei in der Mitte. Der Median wird als ihr Mittel definiert. Die Spannweite berücksichtigt dagegen nur die beiden äußeren Werte und sagt nichts darüber aus, wie die Werte dazwischen verteilt sind. Gleiches Mittel oder gleiche Spannweite beweist daher keine gleiche Datenverteilung. Negative Werte müssen bei Summe und Differenz mit ihrem Vorzeichen eingehen.',
 'Eine Häufigkeitstabelle ist eine abgekürzte Liste. Dreimal 2 und viermal 5 bedeutet 2+2+2+5+5+5+5, nicht bloß zwei gleich häufige Werte. Deshalb ist das Mittel (3·2+4·5)/(3+4). Eine relative Häufigkeit bezieht sich stets auf eine benannte Gesamtzahl. Beobachtete relative Häufigkeiten sind Daten; sie sind nicht automatisch die exakte theoretische Wahrscheinlichkeit des nächsten Versuchs.',
 'Bei einem Balkendiagramm mit Achsenbeginn 20 hat der Balken zum Wert 23 nur die sichtbare Höhe 3. Ein zweiter Wert 27 erzeugt Höhe 7: Das sichtbare Verhältnis 7/3 übertreibt das Datenverhältnis 27/23. Eine Achsenverkürzung muss klar erkennbar sein; ein Nullbeginn verhindert diese spezielle Verhältnisverzerrung. Bei Trends zählen Zeitintervalle: Von Tag 0 bis Tag 2 vergehen zwei Tage, obwohl drei tägliche Messpunkte möglich sind. Wer nur Mitglieder einer Sport-AG befragt, erreicht die anderen Lernenden nicht; die berechnete Auslassungsquote zeigt die Lücke, nicht die genaue Stärke oder Richtung der Verzerrung.'
 ],
 mistakes:'Vor dem Median wirklich sortieren. Bei Häufigkeiten durch die Gesamtzahl der Beobachtungen teilen, nicht durch die Zahl verschiedener Werte. Für Diagrammverhältnisse den Achsenbeginn berücksichtigen und sichtbares Verhältnis von Datenverhältnis trennen. Eine große Stichprobe heilt keine systematisch ausgelassene Gruppe. Ein gemeinsamer Trend ist kein Kausalnachweis.',
 checks:[['Was reagiert meist stärker auf einen einzelnen extrem hohen Wert: Mittel oder Median?','Das Mittel, weil der extreme Wert vollständig in die Summe eingeht. Der Median orientiert sich an der Mitte der sortierten Liste.'],['Zählt die Spannweite die Anzahl verschiedener Werte?','Nein. Sie ist größter minus kleinster Wert und hat dieselbe Einheit wie die Messwerte.'],['Warum ist eine Sport-AG allein keine gute Schulstichprobe zum Sportinteresse?','Die Auswahl hängt gerade mit dem untersuchten Interesse zusammen; andere Lernende werden systematisch nicht erfasst.']],
 summary:'Kennwerte beantworten unterschiedliche Fragen. Mittel verteilt eine Summe, Median sucht die Mitte, Spannweite misst die äußerste Streuung. Häufigkeiten brauchen den richtigen Nenner. Lies Achsen, Zeitintervalle und Auswahlverfahren mit, bevor du aus einer Rechnung eine allgemeine Aussage machst.'
}
];
