// Fiktiver gemeinsamer Kontext. Keine erhobenen Schuldaten oder Marktpreise.
// Zusätzliche Projektfragen sind von den unveränderten Generatorbeispielen getrennt.
export const storyNotice='Unser roter Faden ist ein erfundener Projekttag: Eine neunte Klasse plant einen offenen Nachmittag im Schulhof mit Sitzbereich, kleinen Aktionen und einer Ausstellung. Alle Preise, Maße und Daten in dieser Geschichte sind Übungsannahmen, keine Angaben über eine echte Berliner Schule. Du kannst jedes Kapitel einzeln lesen; den nötigen Anschluss findest du jeweils am Anfang.';
export const stories={
 zahlen:{
 phase:'1 · Die erste Materialliste',
 question:'Reicht das Material für unseren offenen Schulhofnachmittag?',
 opening:[
 'Auf dem Planungstisch liegen Skizzen, Stoffreste und eine noch ziemlich ungeordnete Materialliste. Zwei Gruppen melden ihren Bedarf für ein Banner: drei Viertel und zwei Viertel eines Stoffstücks. Eine andere Gruppe schreibt eine kleine Länge als Dezimalzahl auf, jemand anders mit einer Zehnerpotenz. Bevor ihr bestellen könnt, müssen die Angaben dieselbe Sprache sprechen. Sonst sieht eine lange Zahl wichtiger aus als eine kurze, obwohl beide dieselbe Menge meinen.',
 'Beginne mit einer Schätzung, nicht mit dem Taschenrechner: Reicht ein ganzes Stoffstück für die beiden Gruppen? Zeichne vier gleich große Teile und zähle den Bedarf ein. Diese kleine Entscheidung enthält schon den Kern des Kapitels. Ein Bruch benennt eine Menge, eine Potenz bündelt Faktoren, eine Wurzel sucht zu einer Fläche die passende Seitenlänge. Die Schreibweise soll die Entscheidung erleichtern; sie ersetzt nicht die Frage, was eine Zahl bedeutet.'
 ],
 bridges:[
 ['Gleiche Stücke zählen','Beim Banner sind Viertel die gemeinsame Einheit. Fünf benötigte Viertel passen nicht in vier vorhandene Viertel. Wer die Nenner mitaddiert, würde aus einem Materialmangel plötzlich einen ausreichenden Vorrat machen. Halte deshalb zuerst fest, welche Stückgröße du zählst.'],
 ['Kleiner heißt nicht negativ','Auf der Materialliste kann eine sehr kleine positive Länge stehen. Ein negativer Exponent muss also etwas anderes bedeuten als eine negative Länge. Stelle dir das Kürzen gleicher Faktoren als Rückweg vor: Sobald im Zähler keine Faktoren mehr übrig sind, bleiben die übrigen im Nenner.'],
 ['Blöcke oder einzelne Faktoren?','Beim Zusammenfassen der Liste hilft eine kurze Pause am Rechenzeichen. Werden zwei Bündel aneinandergehängt, wird ein ganzes Bündel wiederholt oder wird etwas addiert? Erst diese Unterscheidung entscheidet über das Potenzgesetz. Eine Regel allein am ähnlichen Aussehen der Zahlen auszuwählen ist unzuverlässig.'],
 ['Eine Seitenlänge abschätzen','Für eine quadratische Ausstellungsfläche von 11 Flächeneinheiten sucht ihr eine Seitenlänge. Drei Einheiten reichen nicht, vier sind zu lang. Ihr könnt also einen brauchbaren Bereich angeben, bevor ihr einen Dezimalwert kennt. Die Wurzel benennt die exakte Länge; die Grenzen helfen beim Planen.']
 ],
 checkpoint:['Ein Stoffstück ist vorhanden. Nach der Bannerplanung fehlen 1/4 Stück. Woran erkennst du den Fehler in „3/4 + 2/4 = 5/8“ ohne neu zu rechnen?','Beide Gruppen brauchen zusammen mehr als ein Ganzes: 3/4 plus 1/4 würde es schon aufbrauchen. 5/8 ist kleiner als 1 und passt nicht zur Situation. Richtig sind 5/4; nach Abzug des vorhandenen Ganzen fehlt 1/4.'],
 synthesis:'Die Materialliste ist jetzt vergleichbar. Beim Banner habt ihr einen fehlenden Viertelanteil erkannt; bei der quadratischen Fläche kennt ihr einen sicheren Längenbereich. Für eure Planung lohnt sich diese Reihenfolge: Bedeutung und Größenordnung klären, dann rechnen, zuletzt die Einheit kontrollieren. Damit könnt ihr auch eine Zahl zurückweisen, die der Rechner korrekt aus einer falsch eingegebenen Rechnung erzeugt hat.',
 next:'Als Nächstes fehlen nicht mehr nur Materialien, sondern Angaben: Welcher Wert muss in einer Abrechnung stehen, damit sie aufgeht? Im Kapitel Gleichungen wird aus dem Schätzen eine systematische Suche nach Unbekannten.'
 },
 gleichungen:{
 phase:'2 · Unbekannte in der Abrechnung',question:'Wie finden wir einen fehlenden Wert, ohne jeden Vorschlag einzeln auszuprobieren?',
 opening:[
 'Die Materialliste ist geordnet. Nun sammelt das Team Abrechnungen und Entwürfe ein. Auf einem Zettel fehlt ein Betrag, auf einem anderen eine Seitenlänge. Raten kann bei kleinen Zahlen funktionieren, wird aber schnell unübersichtlich. Ihr braucht ein Verfahren, bei dem jeder Schritt erklärt, warum keine Lösung verloren geht.',
 'Falls du hier einsteigst: Im ersten Kapitel ging es darum, Anteile und Größen zuverlässig zu lesen. Jetzt steht x für eine noch unbekannte Zahl. Das kann ein Preis sein, muss aber nicht: In einer Bilanz kann x auch eine negative Korrektur sein. Diese Unterscheidung ist wichtig, weil die reine Gleichung zunächst mehr Werte zulässt als manche Sachsituation. Erst nach dem Lösen entscheidet ihr, welche Lösung zur Frage passt.'
 ],
 bridges:[
 ['Eine Buchung rückwärts lesen','Nehmt die Bilanzgleichung 3x+4 = −2 als Rechenmodell für drei gleiche Korrekturen x und eine Gutschrift 4. Die gesamte Änderung beträgt −2. Vermute zunächst das Vorzeichen von x. Um von der Bilanz zurück zur einzelnen Korrektur zu kommen, wird zuerst die Gutschrift entfernt und dann der Rest gleichmäßig aufgeteilt.'],
 ['Beim Entwurf fehlt leicht ein Streifen','Ein quadratischer Entwurf wird in beide Richtungen verlängert. Wer nur das alte Quadrat und ein kleines Eckquadrat addiert, vergisst die beiden seitlichen Streifen. Bevor du die binomische Formel liest, suche diese Streifen in einer Skizze. So bekommt der Mittelterm eine nachvollziehbare Herkunft.'],
 ['Rechnerische Lösung, passende Länge','Bei einem Quadrat mit Fläche 25 liefert die Gleichung x² = 25 zwei reelle Lösungen. Für eine Seitenlänge bleibt nur die positive. Schreibe nicht sofort die negative Lösung aus der Mathematik heraus: Die Gleichung und das Sachmodell stellen verschiedene Bedingungen. Die Übung unten fragt ausdrücklich nach allen reellen Lösungen.'],
 ['Zwei Angaben müssen zugleich stimmen','Eine einzelne Abrechnung kann zu vielen Zahlenpaaren passen. Mit einer zweiten unabhängigen Bedingung wird die Auswahl enger. Beim Addieren eines geeigneten Gleichungspaars verschwindet eine Unbekannte; anschließend muss die gefundene Lösung trotzdem beide ursprünglichen Angaben erfüllen. Eine Probe ist hier keine bloße Wiederholung der letzten Rechenzeile.']
 ],
 checkpoint:['In der Bilanz 3x+4 = −2 soll x negativ sein. Jemand erhält x = 2. Wie prüfst du den Vorschlag, bevor du die ganze Rechnung suchst?','Einsetzen ergibt 3·2+4 = 10 statt −2. Schon das positive Vorzeichen passt nicht zur nötigen Absenkung. Richtig ist x = −2: drei Korrekturen von −2 und die Gutschrift 4 ergeben −2.'],
 synthesis:'Ihr könnt eine fehlende Zahl jetzt durch nachvollziehbare Rückschritte bestimmen. Bei Entwürfen hilft zusätzlich die Produktform: Sie zeigt, wann ein Faktor null wird. Haltet in der Planung beides fest, die vollständige rechnerische Lösung und eine eventuelle Einschränkung wie „Länge positiv“. Sonst bleibt unklar, ob eine Lösung vergessen oder begründet verworfen wurde.',
 next:'Eine einzelne Abrechnung ist damit lösbar. Aber die Kosten ändern sich mit der Ausleihdauer. Im nächsten Kapitel baut ihr eine Vorschrift, die nicht nur für eine Dauer, sondern für alle zulässigen Dauern gilt.'
 },
 linear:{
 phase:'3 · Kosten für verschiedene Dauern',question:'Was kostet der Transport, wenn der Aufbau länger dauert?',
 opening:[
 'Für den Schulhofnachmittag soll ein Leihrad Material transportieren. Im erfundenen Angebot fallen 4 Euro Grundgebühr und 2 Euro je Stunde an. Das Team plant zunächst drei Stunden, möchte aber auch wissen, was eine Verzögerung kostet. Eine einzige Gesamtsumme hilft dabei wenig. Ihr braucht eine Vorschrift, die auf eine andere Dauer sofort eine neue Antwort gibt.',
 'Aus dem Gleichungskapitel kennst du den Rückweg von einer Gesamtsumme zu einer Unbekannten. Eine Funktion beschreibt zuerst den Hinweg: Du wählst eine zulässige Dauer, sie liefert genau einen Preis. Überlege vor der Rechnung, ob doppelte Dauer hier auch doppelten Gesamtpreis bedeutet. Die Grundgebühr bleibt schließlich dieselbe. An diesem Unterschied zwischen festem Betrag und Zuwachs pro Stunde hängt das ganze Modell.'
 ],
 bridges:[
 ['Was kommt pro Stunde dazu?','Beim Leihrad bleiben die zusätzlichen Kosten von einer weiteren Stunde gleich. Im Graphen bedeutet das: Gleich große Schritte nach rechts erzeugen gleich große Schritte nach oben. Die Grundgebühr legt den Startpunkt fest; sie wird nicht bei jeder Stunde erneut bezahlt. Erst daraus entsteht die Kurzform y = mx+b.'],
 ['Eine Angabe ergänzt die andere','Wenn ihr nur den Stundenpreis und einen Gesamtpreis kennt, könnt ihr die Grundgebühr zurückrechnen. Zieht vom Gesamtpreis den zeitabhängigen Anteil ab. Geometrisch heißt das: Von einem bekannten Punkt geht ihr mit der bekannten Steigung bis zur y-Achse zurück. Negative x-Werte in den abstrakten Übungen sind Koordinaten, keine negativen Ausleihzeiten.'],
 ['Gleich teuer ist eine gemeinsame Ausgabe','Bei zwei Angeboten sucht ihr zunächst die Dauer, zu der beide denselben Preis liefern. Das ist eine Gleichung wie im vorigen Kapitel. Erst danach fragt ihr, welches Angebot vor oder nach diesem Punkt günstiger ist. Ein Schnittpunkt bei negativer Dauer wäre rechnerisch korrekt, für die Ausleihe aber nicht erreichbar.'],
 ['Vom Ergebnis zur Entscheidung','Drei Stunden ergeben in unserem Angebot 10 Euro. Bei vier Stunden wären es 12 Euro; eine Stunde Verzögerung kostet also 2 Euro zusätzlich. Damit kann das Team über eine Zeitreserve sprechen. Die Rechnung gilt nur für das vereinbarte Modell: Wenn jede angefangene Stunde voll zählt, braucht ihr zusätzlich eine Regel für nicht ganzzahlige Dauern.']
 ],
 checkpoint:['Das Team verdoppelt die Dauer von drei auf sechs Stunden. Verdoppeln sich auch die 10 Euro? Begründe mit den zwei Preisbestandteilen.','Nein. Der Stundenanteil steigt von 6 auf 12 Euro, die Grundgebühr bleibt 4 Euro. Insgesamt sind es 16 Euro, nicht 20. Nur ein Modell ohne Grundgebühr wäre hier proportional zur Dauer.'],
 synthesis:'Für die Transportplanung könnt ihr nun Kosten und Zeitreserve trennen. Die Steigung beschreibt, wie teuer zusätzliche Zeit wird; der Achsenabschnitt beschreibt, was schon vorher anfällt. Eine Tabelle, ein Graph und eine Formel müssen dieselbe Beziehung zeigen. Kontrolliere deshalb an einem leicht lesbaren Punkt, ob alle Darstellungen zusammenpassen.',
 next:'Für den Preis war die Änderung konstant. Bei einem symmetrischen Entwurf wird der Höhenunterschied dagegen vom Abstand zur Mitte abhängig. Im nächsten Kapitel reicht eine Gerade nicht mehr: Ihr untersucht Parabeln.'
 },
 quadratisch:{
 phase:'4 · Ein symmetrischer Entwurf',question:'Wie bleibt ein Entwurf symmetrisch, wenn wir seine Mitte verschieben?',
 opening:[
 'Die Ausstellungsgruppe zeichnet ein parabelförmiges Muster für eine Stellwand. Links und rechts sollen Markierungen auf gleicher Höhe liegen, die Mitte darf aber noch verschoben werden. Dies ist ein geometrischer Entwurf, keine Bauanleitung und keine Aussage darüber, welche Form belastbar ist. Eure Frage betrifft die Lage von Punkten, nicht die Statik.',
 'Im Kapitel davor stand eine Funktion für gleichmäßige Preisänderungen. Auch hier ordnet eine Funktion jedem x genau ein y zu. Der Unterschied steckt im Quadrat: Doppelt so weit von der Mitte entfernt bedeutet bei unveränderter Parabel einen viermal so großen Höhenunterschied zum Scheitel. Zeichne zuerst eine vermutete Form. Würde eine Gerade zu zwei gleich hohen Punkten auf verschiedenen Seiten einer tiefsten Stelle passen?'
 ],
 bridges:[
 ['Die Mitte über die Null finden','In der Scheitelform wird der Abstand zur Mitte zuerst berechnet und dann quadriert. Suche deshalb nicht nach einem auswendig gelernten Vorzeichenwechsel, sondern nach dem x, das die Klammer null macht. Für den Entwurf ist das der Bezugspunkt, von dem aus ihr alle weiteren Abstände messt.'],
 ['Gleiche Abstände statt zwei Rechnungen','Für f(x) = (x−3)²+4 liegt die Mitte bei x = 3. Eine Markierung bei x = 5 liegt zwei Einheiten rechts davon. Sage zuerst voraus, wo die passende linke Markierung liegt. Das Quadrat macht aus beiden Abständen denselben Höhenbeitrag; ihr müsst die Lage deshalb nicht durch Ausprobieren suchen.'],
 ['Eine Linie kann verfehlt werden','Ob der Entwurf eine Bezugslinie auf Höhe null trifft, hängt von seiner Lage und Öffnung ab. Es kann zwei Schnittstellen geben, nur eine Berührung oder gar keinen Kontakt. Vor dem Wurzelziehen lohnt die Frage, ob das verlangte Quadrat überhaupt nichtnegativ sein kann. Damit erkennst du unmögliche Vorgaben früh.'],
 ['Ein zusätzlicher Punkt legt die Breite fest','Eine Mitte allein bestimmt den Entwurf noch nicht. Viele Parabeln können denselben Scheitel haben. Ein weiterer Punkt außerhalb der Scheitelachse zeigt, welcher Höhenunterschied zu seinem Abstand gehört. Durch Teilen bestimmst du daraus den Streckfaktor. Für den Entwurf heißt das: Die Lage der Mitte und die Öffnungsweite sind getrennte Entscheidungen.']
 ],
 checkpoint:['Bei der Entwurfsfunktion (x−3)²+4 liegt ein Punkt bei x = 5. Wo liegt sein anderer Spiegelpunkt, und warum hat er dieselbe Höhe?','Bei x = 1. Beide Punkte liegen zwei Einheiten von x = 3 entfernt. Die Klammern liefern 2 und −2, beide Quadrate sind 4; die Höhe ist jeweils 8.'],
 synthesis:'Ihr könnt die Mitte des Musters verschieben, gleiche Höhen finden und vor einer Rechnung entscheiden, ob eine Bezugslinie überhaupt erreicht wird. Besonders nützlich ist die Trennung von Lage und Abstand: h und k legen den Scheitel fest, a bestimmt die Höhenänderung gegenüber diesem Scheitel. Eine negative Höhe ist dabei zunächst eine Koordinate relativ zur gewählten Bezugslinie.',
 next:'Der Entwurf steht auf Papier. Für Abstände und Winkel im Schulhof braucht ihr nun andere Beziehungen. Das nächste Kapitel zeigt, welche Angaben ein Dreieck bestimmen und wie du eine passende Formel auswählst.'
 },
 trigonometrie:{
 phase:'5 · Abstände im Plan',question:'Wie bestimmen wir eine schräge Strecke, die wir nicht direkt abmessen?',
 opening:[
 'Auf dem Lageplan verbindet eine schräge Linie zwei Ecken des Ausstellungsbereichs. Die rechtwinkligen Abstände im Modell sind 3 cm und 4 cm. Die direkte Verbindung ist kürzer als der Weg erst entlang der einen und dann entlang der anderen Kante. Aber wie lang ist sie? Diese Frage lässt sich bereits an einer maßstäblichen Zeichnung schätzen, bevor eine Formel zum Einsatz kommt.',
 'Aus den vorigen Kapiteln bringst du Quadrate, Wurzeln und das Umstellen von Gleichungen mit. Für Dreiecke kommt eine neue Gewohnheit dazu: Markiere bekannte Seiten, den gesuchten Wert und vorhandene Winkel. Nicht das Wort „Dreieck“ entscheidet über die Formel, sondern diese Angaben. Ein Lageplan ersetzt außerdem keine Prüfung von Fluchtwegen oder sicheren Befestigungen durch Verantwortliche; wir untersuchen hier nur die Geometrie.'
 ],
 bridges:[
 ['Was bleibt beim Vergrößern gleich?','Ein größer ausgedruckter Lageplan hat längere Seiten, aber dieselben Winkel. Die Seitenverhältnisse bleiben gleich. Sinus, Kosinus und Tangens halten genau solche Verhältnisse fest. Du brauchst deshalb nicht für jede mögliche Dreiecksgröße eine eigene Tabelle. Entscheidend ist, auf welchen Winkel sich Gegen- und Ankathete beziehen.'],
 ['Direkt statt über die Ecke','Im 3-cm-mal-4-cm-Modell muss die Diagonale länger als jede einzelne Kathete, aber kürzer als der 7-cm-Umweg sein. Pythagoras liefert 5 cm und besteht diese Kontrolle. Der Satz addiert Quadratflächen, nicht Strecken. Falls stattdessen ein Winkel gesucht ist, ist der Rückweg über eine trigonometrische Umkehrfunktion nötig.'],
 ['Wenn kein rechter Winkel eingezeichnet ist','Ein dreieckiges Gestaltungselement muss nicht rechtwinklig sein. Dann sind die Kathetenquotienten nicht direkt anwendbar. Mit zwei Winkeln und einer passenden Gegenseite kann der Sinussatz helfen. Zeichne die Gegenüberpaare sichtbar ein; gerade bei gedrehten Skizzen schützt dich das vor dem Vertauschen der Angaben.'],
 ['Den eingeschlossenen Winkel beachten','Sind zwei Seiten und ihr Zwischenwinkel bekannt, lässt sich die dritte Seite mit dem Kosinussatz finden. Derselbe Zwischenwinkel liefert über eine senkrechte Höhe auch die Fläche. Für eure Materialplanung sind das zwei verschiedene Fragen: Randlänge oder Flächeninhalt. Die bekannten Zahlen können gleich sein, der gesuchte Gegenstand ist es nicht.']
 ],
 checkpoint:['Die schräge Verbindung im Modell hat Katheten 3 cm und 4 cm. Ein Vorschlag lautet 7 cm. Welche geometrische Kontrolle spricht dagegen?','7 cm ist der Weg über die rechtwinklige Ecke. Die direkte Verbindung ist kürzer. Mit Pythagoras: c² = 9+16 = 25, also c = 5 cm. Das ist zugleich länger als jede Kathete.'],
 synthesis:'Für den Lageplan habt ihr ein verlässliches Auswahlverfahren: erst die Skizze beschriften, dann die Voraussetzungen prüfen, danach eine Beziehung mit bekannten und gesuchten Größen auswählen. Ein Ergebnis braucht anschließend Einheit und Plausibilitätskontrolle. Die 5 cm gehören zum Modell; für eine reale Länge wäre zusätzlich ein ausdrücklich angegebener Maßstab erforderlich.',
 next:'Eine schräge Strecke begegnet euch gleich wieder: als Mantellinie eines Kegels. Im nächsten Kapitel benutzt ihr das rechtwinklige Schnittdreieck, um Materialbedarf und Rauminhalt auseinanderzuhalten.'
 },
 koerper:{
 phase:'6 · Hülle und Inhalt',question:'Braucht ein größerer Ausstellungsbehälter doppelt so viel Material?',
 opening:[
 'Für die Ausstellung werden geometrische Behälter als Modelle entworfen. Eine Gruppe interessiert sich dafür, wie viel hineinpasst; eine andere will wissen, wie viel Papier die Hülle braucht. Beide fragen nach „der Größe“, meinen aber unterschiedliche Größen. Das zeigt sich spätestens beim Vergrößern: Eine doppelt so lange Kante macht weder die Oberfläche noch das Volumen bloß doppelt so groß.',
 'Falls du direkt hier anfängst: Kreisflächen berechnest du mit πr², schräge Längen in einem rechtwinkligen Schnittdreieck mit Pythagoras. Jetzt geht es darum, diese Bausteine der richtigen Frage zuzuordnen. Zeichne an einem Kegelmodell die senkrechte Höhe und eine schräge Linie zum Rand ein. Welche davon würdest du beim Zuschneiden des Mantels brauchen? Begründe deine Vermutung, bevor du eine Formel auswählst.'
 ],
 bridges:[
 ['Füllen ist eine Raumfrage','Ein kegelförmiges Modell mit Radius 3 cm und senkrechter Höhe 4 cm hat denselben Grundkreis wie ein entsprechender Zylinder, wird aber zur Spitze schmaler. Es muss also weniger fassen. Der bekannte Faktor ein Drittel macht aus dieser Vermutung eine genaue Beziehung. Die Formel setzt die senkrechte Höhe ein, nicht die längere Mantellinie.'],
 ['Zuschneiden ist eine Flächenfrage','Für die Papierhülle interessiert dagegen der Weg auf der schrägen Außenfläche. Die Mantellinie ist im Schnittdreieck die Hypotenuse. Beim Aufrollen des Mantels bleibt sie der Radius des Kreissektors. Überlege außerdem, ob euer Modell einen Boden bekommt: Ein offener Mantel und ein geschlossener Kegel benötigen unterschiedliche Flächen.'],
 ['Vergrößern hat verschiedene Folgen','An einer Kugel ist der Unterschied besonders klar. Verdoppelt ihr den Radius, steckt der Faktor 2 in der Oberfläche zweimal und im Volumen dreimal. Das ist der Grund für vierfachen Flächenbedarf und achtfachen Rauminhalt. Diese Potenzidee stammt aus dem ersten Kapitel; jetzt erklärt sie eine Entwurfsentscheidung.'],
 ['Teile zusammensetzen, Einheiten behalten','Ein Modell aus Zylinder und Halbkugel lässt sich für den Rauminhalt in zwei nicht überlappende Teile zerlegen. An der Verbindungsstelle entsteht aber keine zusätzliche Außenhaut. Das Addieren sämtlicher Einzeloberflächen würde diese Innenfläche mitzählen. Bei sehr kleinen Längen hilft dieselbe Einheitenkontrolle, die ihr schon an der Materialliste gebraucht habt.']
 ],
 checkpoint:['Radius 3 cm, Höhe 4 cm: Für den Kegelmantel setzt jemand M = π·3·4 an. Welcher Wert muss statt 4 verwendet werden?','Die Mantellinie s = √(3²+4²) = 5 cm. Der Mantel hat M = 15π cm². Die 4 cm sind die senkrechte Höhe und gehören zur Volumenrechnung.'],
 synthesis:'Ihr könnt auf dem Entwurf jetzt getrennt vermerken, wie groß Hülle und Inhalt sind. Eine Einheit ist dabei eine inhaltliche Kontrolle: cm² passt zum Papierbedarf, cm³ zum Rauminhalt. Die Volumenformeln behandeln ideale Körper ohne Wandstärke. Für einen echten Behälter müsstet ihr zusätzlich klären, ob Innen- oder Außenmaße gegeben sind.',
 next:'Die räumliche Planung ist vorläufig fertig. Nun verändert sich etwas über mehrere Schritte: Wie entwickelt sich eine Zahl, wenn immer derselbe Anteil dazukommt? Das nächste Kapitel vergleicht Wachstum mit einer Bewegung, die sich wiederholt.'
 },
 wachstum:{
 phase:'7 · Entwicklung oder Wiederholung?',question:'Welche Formel passt zu einer wachsenden Zahl und welche zu einer wiederkehrenden Bewegung?',
 opening:[
 'Für den Schulhofnachmittag diskutiert das Team zwei sehr verschiedene Modelle. In einer Planungsrechnung startet eine Kennzahl bei 300 und wächst je Schritt um 4 Prozent. Daneben soll eine Bildschirmgrafik regelmäßig auf und ab schwingen. Beide Modelle verändern Werte, aber auf verschiedene Weise: Der Bestand nimmt zu, die Schwingung kehrt immer wieder zurück. Wer für beides dieselbe Formel sucht, übersieht die eigentliche Frage.',
 'Die 300 sind hier bewusst eine Modellgröße, keine Vorhersage echter Anmeldungen. Menschen lassen sich nicht in Dezimalbruchteile zerlegen, und ein konstanter prozentualer Zuwachs ist keine Zusage. Du brauchst aus den vorigen Kapiteln Prozentanteile, Potenzen und Funktionswerte. Überlege zuerst: Sind beim zweiten Wachstumsschritt wieder genau 12 Einheiten zusätzlich zu erwarten?'
 ],
 bridges:[
 ['Der neue Bestand wird zur Bezugsgröße','Im ersten Schritt sind 4 Prozent von 300 genau 12. Danach startet ihr aber bei 312. Auch die neu hinzugekommenen 12 werden nun mitverändert. Deshalb ist der nächste Zuwachs etwas größer. Die Potenzschreibweise kürzt diese wiederholte Multiplikation ab; sie ist keine neue Rechenoperation für Prozentzahlen.'],
 ['Rückwärts muss jeder Schritt zurück','Wenn ihr nur den Endbestand kennt, müsst ihr jede Multiplikation wieder rückgängig machen. Bei Verdopplung und Halbierung lässt sich das besonders gut im Kopf verfolgen. Ein Halbierungsmodell zieht nicht jedes Mal dieselbe Menge ab. Für reale Vorräte wird es spätestens dann unpassend, wenn einzelne unteilbare Gegenstände übrig bleiben.'],
 ['Die Grafik kehrt zur Mitte zurück','Die Bildschirmgrafik soll sich nicht endlos vom Startwert entfernen. Ein Sinusmodell beschreibt eine Auslenkung relativ zur Mittellinie: negative Werte liegen auf der anderen Seite dieser Linie. Sie sind keine negative Bildschirmhöhe. Der äußere Faktor legt fest, wie weit die Grafik maximal ausschlägt; ein Minus kehrt die Richtung um.'],
 ['Höher ist nicht schneller','Wenn sich die Grafik öfter im gleichen Winkelbereich wiederholt, muss sich der innere Winkel schneller ändern. Dafür steht b. Ein größerer äußerer Faktor a macht sie dagegen höher. Hier wird x ausdrücklich in Grad gemessen, nicht in Sekunden. Ein Zeitmodell bräuchte eine zusätzliche Zuordnung zwischen Zeit und Winkel.']
 ],
 checkpoint:['Vergleiche nach zwei Schritten: jedes Mal 12 hinzu oder jedes Mal 4 Prozent mehr, jeweils ab 300. Welches Modell liefert mehr, und warum?','Linear: 300+12+12 = 324. Prozentual: 300·1,04·1,04 = 324,48. Im zweiten Fall beträgt der zweite Zuwachs 4 Prozent von 312, also 12,48. Die Bezugsgröße ist mitgewachsen.'],
 synthesis:'Das Team kann nun unterscheiden, was seine Formel behauptet. Ein konstanter Betrag führt zu linearer Änderung, ein konstanter Faktor zu exponentieller Änderung, eine regelmäßige Rückkehr zu einem periodischen Modell. Bevor ihr Zahlen einsetzt, benennt Schrittgröße beziehungsweise Winkel und die Bedeutung der Ausgabe. Erst dann lässt sich beurteilen, ob das Ergebnis für eure Planung nützlich ist.',
 next:'Selbst mit einem Modell bleiben einzelne Ergebnisse ungewiss. Für eine Ziehaktion auf dem Nachmittag braucht ihr deshalb keine Wachstumsprognose, sondern Wahrscheinlichkeiten. Im nächsten Kapitel entscheidet schon das Wort „mindestens“, welche Wege zählen.'
 },
 zufall:{
 phase:'8 · Eine Ziehaktion erklären',question:'Welche Chance versprechen wir bei zwei Ziehungen wirklich?',
 opening:[
 'Für eine kleine Ziehaktion liegen im Modell drei rote und vier blaue gleichartige Kugeln bereit. Das Team muss die Regeln schriftlich festlegen: Wird zurückgelegt? Zählt genau eine rote Kugel oder mindestens eine? Die Unterschiede wirken sprachlich klein, verändern aber die Chance. Eine verständliche Regel gehört deshalb genauso zur Planung wie die Rechnung.',
 'Du brauchst Bruchanteile und Multiplikation aus dem ersten Kapitel. Anders als bei den Bestandsmodellen im vorigen Kapitel lässt sich das einzelne Ergebnis nicht vorhersagen. Die Wahrscheinlichkeit beschreibt das Modell des Versuchs. Vermute vor dem Rechnen, ob zwei rote Kugeln ohne Zurücklegen eher oder weniger wahrscheinlich sind als mit Zurücklegen. Denke dabei an den Inhalt der Urne nach dem ersten roten Zug.'
 ],
 bridges:[
 ['Ein Anteil innerhalb eines Anteils','Ein Baumdiagramm sortiert zunächst mögliche Abläufe. Ein Zweig auf der zweiten Stufe fragt nicht erneut nach allen Versuchen, sondern nach den Versuchen, die schon den ersten Zweig genommen haben. Deshalb werden Anteile entlang eines vollständigen Weges multipliziert. Erst danach steht fest, welchen Anteil aller Abläufe dieser Weg bildet.'],
 ['Die Regel verändert die zweite Chance','Ohne Zurücklegen enthält die Urne nach einem roten Zug weniger rote Kugeln. Nach einem blauen Zug sieht sie anders aus. Schreibt diese Zwischenbestände neben die Skizze, bevor ihr Brüche notiert. So erklärt ihr die Regeln der Aktion und könnt den zweiten Nenner begründen, statt ihn nur nach einem Merksatz zu verkleinern.'],
 ['Genau und mindestens sind andere Ereignisse','Auf dem Aushang soll stehen, welche Abläufe zählen. Bei „genau einmal rot“ sind RB und BR passend; RR ist ausdrücklich ausgeschlossen. Bei „mindestens einmal rot“ kommt RR dazu. Die Gegenereignismethode kann die Rechnung verkürzen, aber erst nachdem ihr den unpassenden Rest eindeutig bestimmt habt.'],
 ['Eine Erwartung ist kein Versprechen','Wie viele mögliche Menüs eine Aktion anbietet, ist eine Anzahl von Kombinationen. Wie viele rote Ziehungen im Mittel erwartet werden, ist dagegen Versuchszahl mal Chance. Das Team darf aus einem solchen Mittelwert keine Garantie für einen einzelnen Nachmittag machen. Eine beobachtete Abweichung allein beweist auch noch nicht, dass die Ziehung unfair war.']
 ],
 checkpoint:['Der Aushang verspricht „mindestens einmal rot“ bei zwei Zügen. Jemand zählt nur RB und BR. Welcher Ablauf fehlt, und welcher bleibt ausgeschlossen?','RR fehlt: Auch zweimal rot erfüllt mindestens einmal rot. Ausgeschlossen bleibt nur BB. Mit Zurücklegen ist die Chance deshalb 1−(4/7)² = 33/49.'],
 synthesis:'Eure Ziehregeln lassen sich jetzt als vollständige Pfade prüfen. Entscheidet zuerst, welche Abläufe dazugehören und ob sich die Urne verändert. Dann erst kommen Produkt, Summe oder Gegenereignis. Für Teilnehmende sollte aus dem Text dieselbe Regel hervorgehen wie aus eurer Rechnung; sonst ist auch eine fehlerfrei berechnete Zahl keine verständliche Auskunft.',
 next:'Nach dem Nachmittag habt ihr Beobachtungen statt bloßer Erwartungen. Im letzten Kapitel prüft ihr, wie man diese Daten zusammenfasst und zeigt, ohne mehr zu behaupten, als sie hergeben.'
 },
 daten:{
 phase:'9 · Den Nachmittag ehrlich auswerten',question:'Was können wir nach dem Projekttag aus unseren Daten schließen?',
 opening:[
 'Der erfundene Schulhofnachmittag ist vorbei. Für die Auswertung liegen Rückmeldungen und Zählungen vor. Das Team möchte den anderen Klassen zeigen, was funktioniert hat. Ein einzelner Durchschnitt und ein auffälliges Balkendiagramm wären schnell erstellt. Aber beantworten sie die richtige Frage? Und wurden auch die Menschen gefragt, deren Perspektive bisher fehlt?',
 'Aus dem Zufallskapitel kennst du den Unterschied zwischen theoretischer Chance und tatsächlich beobachtetem Anteil. Hier arbeitest du mit Beobachtungen. Du brauchst sicheres Addieren, Sortieren und Prozentrechnen. Beginne diesmal vor jeder Rechnung mit einem Satz: Welche Gruppe wurde betrachtet, und was wurde gemessen? Ohne diese Angaben kann eine Zahl korrekt sein und trotzdem zu einer falschen Schlussfolgerung führen.'
 ],
 bridges:[
 ['Eine Summe verteilen oder die Mitte suchen','Beim Auswerten können euch zwei Fragen interessieren: Welcher gleiche Wert würde dieselbe Gesamtsumme ergeben? Oder welcher Wert liegt in der Mitte der sortierten Beobachtungen? Das sind Mittelwert und Median. Wenn ein einzelner ungewöhnlich hoher Wert auftaucht, reagieren sie verschieden. Überlege vor dem Rechnen, welche Frage euer Bericht tatsächlich beantworten soll.'],
 ['Negative Werte brauchen eine Bedeutung','Die abstrakte Übungsliste 3, 4, 2, −2 kann zum Beispiel Abweichungen von einer geplanten Zeit in Minuten beschreiben: −2 bedeutet zwei Minuten früher. Sie wäre keine Liste von Besucherzahlen. Sortiert man sie, rückt −2 nach vorn. Die Spannweite zeigt dann den Abstand zwischen frühester und spätester Abweichung, nicht die Anzahl der Beobachtungen.'],
 ['Häufigkeiten sind abgekürzte Beobachtungen','Wenn dieselbe Bewertung mehrfach vorkommt, könnt ihr eine Tabelle führen statt jede Nennung auszuschreiben. Beim Mittel muss trotzdem jede Nennung zählen. Ebenso braucht jeder Prozentanteil eine klar benannte Gesamtzahl. Ein Anteil unter den Befragten ist nicht automatisch der Anteil unter allen, die zum Nachmittag hätten kommen können.'],
 ['Ein überzeugendes Bild kann übertreiben','Für den Bericht vergleicht ihr die Modellwerte 23 und 27. Eine bei 20 beginnende Balkenachse macht aus einem mäßigen Unterschied einen viel größeren sichtbaren Größenvergleich. Prüft zusätzlich, wen eure Umfrage erreicht hat. Mehr Antworten aus nur einer AG ersetzen nicht die Perspektiven der anderen Lernenden. Auch ein steigender Trend erklärt für sich allein keine Ursache.']
 ],
 checkpoint:['Die Zeitabweichungen lauten 3, 4, 2, −2 Minuten. Sind Mittelwert und Median gleich? Notiere zuerst die sortierte Liste.','Sortiert: −2, 2, 3, 4. Das Mittel ist 7/4 = 1,75 Minuten; der Median ist (2+3)/2 = 2,5 Minuten. Die Spannweite beträgt 4−(−2) = 6 Minuten. Die Kennwerte beantworten verschiedene Fragen.'],
 synthesis:'Euer Abschlussbericht kann nun auch seine Grenzen zeigen: Welche Daten liegen vor, welchen Kennwert habt ihr gewählt und wer wurde nicht erfasst? Die Rechnung mit einem Anteil verbindet dieses Kapitel mit der ersten Materialliste. Dazwischen habt ihr Unbekannte bestimmt, Modelle verglichen und geometrische Größen getrennt. Bei jedem Schritt war die wichtigste Kontrolle dieselbe: Passt die mathematische Aussage zu der Entscheidung, die ihr treffen wollt?',
 next:'Der rote Faden endet mit einer begründeten Auswertung, nicht mit dem Anspruch, alles vorhersehen zu können. Wähle zum Weiterüben eine Methode, bei der du die Rechnung erklären, aber noch nicht sicher allein durchführen kannst. Die direkte Übung und der Rücklink zum Beispiel helfen dir, genau diese Lücke zu schließen.'
 }
};

// Bewusst nur dort ein neues Schaubild, wo die Anordnung eine Beziehung erklärt.
// Vollständiger Inhalt ist semantisches HTML: responsive, ohne JS und ohne Farbcodierung lesbar.
export const processFigures={
 gleichungen:{title:'Eine Bilanz vorwärts und rückwärts',guidance:'Lies zuerst die obere Rechenkette. Decke danach die untere ab und sage voraus, welche Umkehroperation zuerst nötig ist. Die Reihenfolge kehrt sich um.',tracks:[['Vorwärts: eine Korrektur wird zur Bilanz','x = −2','· 3 → −6','+ 4 → −2'],['Rückwärts: aus der Bilanz wird eine Korrektur','Bilanz −2','− 4 → −6',': 3 → x = −2']],caption:'Die zweimal auftauchende −2 hat unterschiedliche Rollen: links die einzelne Korrektur, rechts die gesamte Bilanz. Rückwärts wird zuerst die letzte Operation aufgehoben. Beide Seiten einer Gleichung müssen dieselbe Umformung erfahren.'},
 linear:{title:'Grundgebühr und Zeitanteil getrennt halten',guidance:'Vergleiche die beiden Zeilen. Welcher Baustein bleibt gleich, welcher wächst? Begründe damit, warum doppelte Dauer hier nicht doppelten Gesamtpreis bedeutet.',tracks:[['Drei Stunden','Grundgebühr 4 €','2 €/h · 3 h = 6 €','Gesamt: 10 €'],['Sechs Stunden','Grundgebühr 4 €','2 €/h · 6 h = 12 €','Gesamt: 16 €']],caption:'Jede Zeile zerlegt die Gesamtkosten in einen festen und einen zeitabhängigen Teil. Von drei auf sechs Stunden kommen 6 Euro hinzu. Die gleichbleibende Grundgebühr verhindert eine Verdopplung des Gesamtpreises.'},
 wachstum:{title:'Gleicher Anfang, anderer zweiter Schritt',guidance:'Beide Reihen starten bei 300 und erreichen zunächst 312. Sage voraus, ob auch der nächste Wert übereinstimmt. Verfolge dann die beschrifteten Operationen.',tracks:[['Konstanter Betrag: immer +12','Start: 300','+ 12 → 312','+ 12 → 324'],['Konstanter Faktor: immer ·1,04','Start: 300','· 1,04 → 312','· 1,04 → 324,48']],caption:'Im ersten Schritt ist der Unterschied unsichtbar. Im zweiten beträgt der prozentuale Zuwachs 12,48, weil er sich auf 312 bezieht. Ein gleiches Wertepaar reicht deshalb nicht aus, um lineares und exponentielles Wachstum zu unterscheiden.'}
};
